apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dgraph
spec:
  serviceName: "dgraph"
  replicas: 1
  selector:
    matchLabels:
      app: qmstr
  template:
    spec:
      containers:
        - name: ratel
          image: dgraph/dgraph:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http-ratel
          command:
            - dgraph-ratel
        - name: zero
          image: dgraph/dgraph:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5080
              name: grpc-zero
            - containerPort: 6080
              name: http-zero
          volumeMounts:
            - name: datadir
              mountPath: /dgraph
          command:
            - bash
            - "-c"
            - |
              set -ex
              dgraph zero --my=$(hostname -f):5080
        - name: alpha
          image: dgraph/dgraph:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http-alpha
            - containerPort: 9080
              name: grpc-alpha
          volumeMounts:
            - name: datadir
              mountPath: /dgraph
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - bash
            - "-c"
            - |
              set -ex
              dgraph alpha --whitelist 10.0.0.0/0 --my=$(hostname -f):7080 --lru_mb 2048 --zero dgraph-0.dgraph.${POD_NAMESPACE}.svc.cluster.local:5080
      terminationGracePeriodSeconds: 60
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
          volume.alpha.kubernetes.io/storage-class: anything
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
