// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analyzerservice.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnalyzerConfigRequest struct {
	AnalyzerID           int32    `protobuf:"varint,1,opt,name=analyzerID,proto3" json:"analyzerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyzerConfigRequest) Reset()         { *m = AnalyzerConfigRequest{} }
func (m *AnalyzerConfigRequest) String() string { return proto.CompactTextString(m) }
func (*AnalyzerConfigRequest) ProtoMessage()    {}
func (*AnalyzerConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd400d4a2b5e8aa, []int{0}
}

func (m *AnalyzerConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzerConfigRequest.Unmarshal(m, b)
}
func (m *AnalyzerConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzerConfigRequest.Marshal(b, m, deterministic)
}
func (m *AnalyzerConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzerConfigRequest.Merge(m, src)
}
func (m *AnalyzerConfigRequest) XXX_Size() int {
	return xxx_messageInfo_AnalyzerConfigRequest.Size(m)
}
func (m *AnalyzerConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzerConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzerConfigRequest proto.InternalMessageInfo

func (m *AnalyzerConfigRequest) GetAnalyzerID() int32 {
	if m != nil {
		return m.AnalyzerID
	}
	return 0
}

type AnalyzerConfigResponse struct {
	ConfigMap            map[string]string   `protobuf:"bytes,2,rep,name=configMap,proto3" json:"configMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PathSub              []*PathSubstitution `protobuf:"bytes,3,rep,name=pathSub,proto3" json:"pathSub,omitempty"`
	Token                int64               `protobuf:"varint,4,opt,name=token,proto3" json:"token,omitempty"`
	Name                 string              `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AnalyzerConfigResponse) Reset()         { *m = AnalyzerConfigResponse{} }
func (m *AnalyzerConfigResponse) String() string { return proto.CompactTextString(m) }
func (*AnalyzerConfigResponse) ProtoMessage()    {}
func (*AnalyzerConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd400d4a2b5e8aa, []int{1}
}

func (m *AnalyzerConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzerConfigResponse.Unmarshal(m, b)
}
func (m *AnalyzerConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzerConfigResponse.Marshal(b, m, deterministic)
}
func (m *AnalyzerConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzerConfigResponse.Merge(m, src)
}
func (m *AnalyzerConfigResponse) XXX_Size() int {
	return xxx_messageInfo_AnalyzerConfigResponse.Size(m)
}
func (m *AnalyzerConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzerConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzerConfigResponse proto.InternalMessageInfo

func (m *AnalyzerConfigResponse) GetConfigMap() map[string]string {
	if m != nil {
		return m.ConfigMap
	}
	return nil
}

func (m *AnalyzerConfigResponse) GetPathSub() []*PathSubstitution {
	if m != nil {
		return m.PathSub
	}
	return nil
}

func (m *AnalyzerConfigResponse) GetToken() int64 {
	if m != nil {
		return m.Token
	}
	return 0
}

func (m *AnalyzerConfigResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InfoNodeMessage struct {
	Token                int64     `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  string    `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Infonode             *InfoNode `protobuf:"bytes,3,opt,name=infonode,proto3" json:"infonode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InfoNodeMessage) Reset()         { *m = InfoNodeMessage{} }
func (m *InfoNodeMessage) String() string { return proto.CompactTextString(m) }
func (*InfoNodeMessage) ProtoMessage()    {}
func (*InfoNodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd400d4a2b5e8aa, []int{2}
}

func (m *InfoNodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoNodeMessage.Unmarshal(m, b)
}
func (m *InfoNodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoNodeMessage.Marshal(b, m, deterministic)
}
func (m *InfoNodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoNodeMessage.Merge(m, src)
}
func (m *InfoNodeMessage) XXX_Size() int {
	return xxx_messageInfo_InfoNodeMessage.Size(m)
}
func (m *InfoNodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoNodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InfoNodeMessage proto.InternalMessageInfo

func (m *InfoNodeMessage) GetToken() int64 {
	if m != nil {
		return m.Token
	}
	return 0
}

func (m *InfoNodeMessage) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *InfoNodeMessage) GetInfonode() *InfoNode {
	if m != nil {
		return m.Infonode
	}
	return nil
}

type DiagnosticNodeMessage struct {
	Token                int64           `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  string          `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Diagnosticnode       *DiagnosticNode `protobuf:"bytes,3,opt,name=diagnosticnode,proto3" json:"diagnosticnode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DiagnosticNodeMessage) Reset()         { *m = DiagnosticNodeMessage{} }
func (m *DiagnosticNodeMessage) String() string { return proto.CompactTextString(m) }
func (*DiagnosticNodeMessage) ProtoMessage()    {}
func (*DiagnosticNodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd400d4a2b5e8aa, []int{3}
}

func (m *DiagnosticNodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnosticNodeMessage.Unmarshal(m, b)
}
func (m *DiagnosticNodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnosticNodeMessage.Marshal(b, m, deterministic)
}
func (m *DiagnosticNodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnosticNodeMessage.Merge(m, src)
}
func (m *DiagnosticNodeMessage) XXX_Size() int {
	return xxx_messageInfo_DiagnosticNodeMessage.Size(m)
}
func (m *DiagnosticNodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnosticNodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnosticNodeMessage proto.InternalMessageInfo

func (m *DiagnosticNodeMessage) GetToken() int64 {
	if m != nil {
		return m.Token
	}
	return 0
}

func (m *DiagnosticNodeMessage) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DiagnosticNodeMessage) GetDiagnosticnode() *DiagnosticNode {
	if m != nil {
		return m.Diagnosticnode
	}
	return nil
}

type SendResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd400d4a2b5e8aa, []int{4}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DummyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyRequest) Reset()         { *m = DummyRequest{} }
func (m *DummyRequest) String() string { return proto.CompactTextString(m) }
func (*DummyRequest) ProtoMessage()    {}
func (*DummyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd400d4a2b5e8aa, []int{5}
}

func (m *DummyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyRequest.Unmarshal(m, b)
}
func (m *DummyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyRequest.Marshal(b, m, deterministic)
}
func (m *DummyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyRequest.Merge(m, src)
}
func (m *DummyRequest) XXX_Size() int {
	return xxx_messageInfo_DummyRequest.Size(m)
}
func (m *DummyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DummyRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AnalyzerConfigRequest)(nil), "service.AnalyzerConfigRequest")
	proto.RegisterType((*AnalyzerConfigResponse)(nil), "service.AnalyzerConfigResponse")
	proto.RegisterMapType((map[string]string)(nil), "service.AnalyzerConfigResponse.ConfigMapEntry")
	proto.RegisterType((*InfoNodeMessage)(nil), "service.InfoNodeMessage")
	proto.RegisterType((*DiagnosticNodeMessage)(nil), "service.DiagnosticNodeMessage")
	proto.RegisterType((*SendResponse)(nil), "service.SendResponse")
	proto.RegisterType((*DummyRequest)(nil), "service.DummyRequest")
}

func init() { proto.RegisterFile("analyzerservice.proto", fileDescriptor_8bd400d4a2b5e8aa) }

var fileDescriptor_8bd400d4a2b5e8aa = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xc7, 0xb3, 0x71, 0xdb, 0x34, 0xd3, 0x3e, 0x49, 0xbb, 0x7a, 0x52, 0x96, 0x1c, 0x4a, 0xe4,
	0x93, 0x2f, 0x58, 0x28, 0x3d, 0x80, 0x10, 0x12, 0xa2, 0x0d, 0x54, 0x95, 0x28, 0xa0, 0x8d, 0x84,
	0xb8, 0x6e, 0xed, 0x89, 0xbb, 0x6a, 0xbc, 0xeb, 0x7a, 0xd7, 0x95, 0xc2, 0x09, 0x89, 0xaf, 0xc6,
	0x07, 0x43, 0x7e, 0x8d, 0x53, 0x0a, 0x48, 0xdc, 0x76, 0xc6, 0x33, 0xbf, 0xff, 0xbc, 0x19, 0x46,
	0x42, 0x89, 0xe5, 0xea, 0x2b, 0xa6, 0x06, 0xd3, 0x3b, 0x19, 0xa0, 0x9f, 0xa4, 0xda, 0x6a, 0xda,
	0xab, 0xcc, 0xf1, 0x30, 0x14, 0x56, 0xc4, 0x3a, 0xc4, 0x65, 0xf9, 0xc5, 0x7d, 0x0e, 0xa3, 0x37,
	0x55, 0xca, 0x99, 0x56, 0x0b, 0x19, 0x71, 0xbc, 0xcd, 0xd0, 0x58, 0x7a, 0x0c, 0x50, 0xb3, 0x2e,
	0x66, 0x8c, 0x4c, 0x88, 0xb7, 0xcd, 0x5b, 0x1e, 0xf7, 0x7b, 0x17, 0x8e, 0xee, 0x67, 0x9a, 0x44,
	0x2b, 0x83, 0xf4, 0x3d, 0xf4, 0x83, 0xc2, 0x73, 0x29, 0x12, 0xd6, 0x9d, 0x38, 0xde, 0xde, 0xd4,
	0xf7, 0xeb, 0x82, 0x1e, 0xce, 0xf1, 0xcf, 0xea, 0x84, 0xb7, 0xca, 0xa6, 0x2b, 0xbe, 0x06, 0xd0,
	0x13, 0xe8, 0x25, 0xc2, 0x5e, 0xcf, 0xb3, 0x2b, 0xe6, 0x14, 0xac, 0xc7, 0x0d, 0xeb, 0x53, 0xe9,
	0x37, 0x56, 0xda, 0xcc, 0x4a, 0xad, 0x78, 0x1d, 0x49, 0xff, 0x87, 0x6d, 0xab, 0x6f, 0x50, 0xb1,
	0xad, 0x09, 0xf1, 0x1c, 0x5e, 0x1a, 0x94, 0xc2, 0x96, 0x12, 0x31, 0xb2, 0x9d, 0x09, 0xf1, 0xfa,
	0xbc, 0x78, 0x8f, 0x5f, 0xc1, 0x60, 0x53, 0x9b, 0x1e, 0x80, 0x73, 0x83, 0xab, 0xa2, 0xe5, 0x3e,
	0xcf, 0x9f, 0x39, 0xed, 0x4e, 0x2c, 0x33, 0x64, 0xdd, 0xc2, 0x57, 0x1a, 0x2f, 0xbb, 0x2f, 0x88,
	0x7b, 0x0d, 0xc3, 0x0b, 0xb5, 0xd0, 0x1f, 0x74, 0x88, 0x97, 0x68, 0x8c, 0x88, 0x70, 0x2d, 0x4d,
	0xda, 0xd2, 0x07, 0xe0, 0x64, 0x32, 0xac, 0x00, 0xf9, 0x93, 0x3e, 0x85, 0x5d, 0xa9, 0x16, 0x5a,
	0xe9, 0x10, 0x99, 0x33, 0x21, 0xde, 0xde, 0xf4, 0xb0, 0x69, 0xac, 0x66, 0xf2, 0x26, 0xc4, 0xfd,
	0x46, 0x60, 0x34, 0x93, 0x22, 0x52, 0xda, 0x58, 0x19, 0xfc, 0x8b, 0xe0, 0x6b, 0x18, 0x84, 0x0d,
	0xa0, 0x25, 0xfb, 0xa8, 0x91, 0xdd, 0xe4, 0xf3, 0x7b, 0xe1, 0xae, 0x07, 0xfb, 0x73, 0x54, 0x61,
	0xb3, 0x67, 0x06, 0x3d, 0x93, 0x05, 0x01, 0x1a, 0x53, 0x48, 0xef, 0xf2, 0xda, 0x74, 0x07, 0xb0,
	0x3f, 0xcb, 0xe2, 0x78, 0x55, 0x1d, 0xd3, 0xf4, 0x47, 0x17, 0x86, 0xc5, 0xe2, 0x8d, 0x34, 0xf3,
	0x52, 0x8c, 0x7e, 0x86, 0xc3, 0x73, 0xb4, 0x9b, 0xe7, 0x40, 0x8f, 0x7f, 0x7b, 0x27, 0x05, 0x68,
	0xfc, 0xe4, 0x2f, 0x77, 0xe4, 0x76, 0xe8, 0x0c, 0xfe, 0xcb, 0xab, 0xac, 0x47, 0x68, 0x28, 0xfb,
	0x65, 0xac, 0xd5, 0xe4, 0xc6, 0xa3, 0xe6, 0x4b, 0xbb, 0x2f, 0xb7, 0xe3, 0x11, 0xfa, 0x11, 0x68,
	0xee, 0xdb, 0x9c, 0x48, 0xab, 0xbc, 0x07, 0x57, 0xf1, 0x27, 0xe0, 0x29, 0xd0, 0x73, 0xb4, 0x73,
	0x9d, 0xa5, 0x01, 0xbe, 0x93, 0x4b, 0x2c, 0x6b, 0x5b, 0x27, 0xb4, 0xe7, 0x35, 0x5e, 0x5f, 0x42,
	0x1d, 0xea, 0x76, 0x9e, 0x91, 0x53, 0x06, 0x47, 0x3a, 0x8d, 0xfc, 0xdb, 0xd8, 0xd8, 0xd4, 0x8f,
	0xd2, 0x24, 0xa8, 0xc3, 0xbe, 0x74, 0xae, 0x76, 0x8a, 0xff, 0xf9, 0xe4, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xee, 0xfe, 0xce, 0xc6, 0x02, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnalysisServiceClient is the client API for AnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnalysisServiceClient interface {
	GetAnalyzerConfig(ctx context.Context, in *AnalyzerConfigRequest, opts ...grpc.CallOption) (*AnalyzerConfigResponse, error)
	SendInfoNodes(ctx context.Context, opts ...grpc.CallOption) (AnalysisService_SendInfoNodesClient, error)
	SendDiagnosticNode(ctx context.Context, opts ...grpc.CallOption) (AnalysisService_SendDiagnosticNodeClient, error)
	GetSourceFileNodes(ctx context.Context, in *DummyRequest, opts ...grpc.CallOption) (AnalysisService_GetSourceFileNodesClient, error)
}

type analysisServiceClient struct {
	cc *grpc.ClientConn
}

func NewAnalysisServiceClient(cc *grpc.ClientConn) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) GetAnalyzerConfig(ctx context.Context, in *AnalyzerConfigRequest, opts ...grpc.CallOption) (*AnalyzerConfigResponse, error) {
	out := new(AnalyzerConfigResponse)
	err := c.cc.Invoke(ctx, "/service.AnalysisService/GetAnalyzerConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) SendInfoNodes(ctx context.Context, opts ...grpc.CallOption) (AnalysisService_SendInfoNodesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AnalysisService_serviceDesc.Streams[0], "/service.AnalysisService/SendInfoNodes", opts...)
	if err != nil {
		return nil, err
	}
	x := &analysisServiceSendInfoNodesClient{stream}
	return x, nil
}

type AnalysisService_SendInfoNodesClient interface {
	Send(*InfoNodeMessage) error
	CloseAndRecv() (*SendResponse, error)
	grpc.ClientStream
}

type analysisServiceSendInfoNodesClient struct {
	grpc.ClientStream
}

func (x *analysisServiceSendInfoNodesClient) Send(m *InfoNodeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *analysisServiceSendInfoNodesClient) CloseAndRecv() (*SendResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *analysisServiceClient) SendDiagnosticNode(ctx context.Context, opts ...grpc.CallOption) (AnalysisService_SendDiagnosticNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AnalysisService_serviceDesc.Streams[1], "/service.AnalysisService/SendDiagnosticNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &analysisServiceSendDiagnosticNodeClient{stream}
	return x, nil
}

type AnalysisService_SendDiagnosticNodeClient interface {
	Send(*DiagnosticNodeMessage) error
	CloseAndRecv() (*SendResponse, error)
	grpc.ClientStream
}

type analysisServiceSendDiagnosticNodeClient struct {
	grpc.ClientStream
}

func (x *analysisServiceSendDiagnosticNodeClient) Send(m *DiagnosticNodeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *analysisServiceSendDiagnosticNodeClient) CloseAndRecv() (*SendResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *analysisServiceClient) GetSourceFileNodes(ctx context.Context, in *DummyRequest, opts ...grpc.CallOption) (AnalysisService_GetSourceFileNodesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AnalysisService_serviceDesc.Streams[2], "/service.AnalysisService/GetSourceFileNodes", opts...)
	if err != nil {
		return nil, err
	}
	x := &analysisServiceGetSourceFileNodesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AnalysisService_GetSourceFileNodesClient interface {
	Recv() (*FileNode, error)
	grpc.ClientStream
}

type analysisServiceGetSourceFileNodesClient struct {
	grpc.ClientStream
}

func (x *analysisServiceGetSourceFileNodesClient) Recv() (*FileNode, error) {
	m := new(FileNode)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AnalysisServiceServer is the server API for AnalysisService service.
type AnalysisServiceServer interface {
	GetAnalyzerConfig(context.Context, *AnalyzerConfigRequest) (*AnalyzerConfigResponse, error)
	SendInfoNodes(AnalysisService_SendInfoNodesServer) error
	SendDiagnosticNode(AnalysisService_SendDiagnosticNodeServer) error
	GetSourceFileNodes(*DummyRequest, AnalysisService_GetSourceFileNodesServer) error
}

// UnimplementedAnalysisServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAnalysisServiceServer struct {
}

func (*UnimplementedAnalysisServiceServer) GetAnalyzerConfig(ctx context.Context, req *AnalyzerConfigRequest) (*AnalyzerConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnalyzerConfig not implemented")
}
func (*UnimplementedAnalysisServiceServer) SendInfoNodes(srv AnalysisService_SendInfoNodesServer) error {
	return status.Errorf(codes.Unimplemented, "method SendInfoNodes not implemented")
}
func (*UnimplementedAnalysisServiceServer) SendDiagnosticNode(srv AnalysisService_SendDiagnosticNodeServer) error {
	return status.Errorf(codes.Unimplemented, "method SendDiagnosticNode not implemented")
}
func (*UnimplementedAnalysisServiceServer) GetSourceFileNodes(req *DummyRequest, srv AnalysisService_GetSourceFileNodesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSourceFileNodes not implemented")
}

func RegisterAnalysisServiceServer(s *grpc.Server, srv AnalysisServiceServer) {
	s.RegisterService(&_AnalysisService_serviceDesc, srv)
}

func _AnalysisService_GetAnalyzerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetAnalyzerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.AnalysisService/GetAnalyzerConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetAnalyzerConfig(ctx, req.(*AnalyzerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_SendInfoNodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalysisServiceServer).SendInfoNodes(&analysisServiceSendInfoNodesServer{stream})
}

type AnalysisService_SendInfoNodesServer interface {
	SendAndClose(*SendResponse) error
	Recv() (*InfoNodeMessage, error)
	grpc.ServerStream
}

type analysisServiceSendInfoNodesServer struct {
	grpc.ServerStream
}

func (x *analysisServiceSendInfoNodesServer) SendAndClose(m *SendResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *analysisServiceSendInfoNodesServer) Recv() (*InfoNodeMessage, error) {
	m := new(InfoNodeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AnalysisService_SendDiagnosticNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalysisServiceServer).SendDiagnosticNode(&analysisServiceSendDiagnosticNodeServer{stream})
}

type AnalysisService_SendDiagnosticNodeServer interface {
	SendAndClose(*SendResponse) error
	Recv() (*DiagnosticNodeMessage, error)
	grpc.ServerStream
}

type analysisServiceSendDiagnosticNodeServer struct {
	grpc.ServerStream
}

func (x *analysisServiceSendDiagnosticNodeServer) SendAndClose(m *SendResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *analysisServiceSendDiagnosticNodeServer) Recv() (*DiagnosticNodeMessage, error) {
	m := new(DiagnosticNodeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AnalysisService_GetSourceFileNodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DummyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalysisServiceServer).GetSourceFileNodes(m, &analysisServiceGetSourceFileNodesServer{stream})
}

type AnalysisService_GetSourceFileNodesServer interface {
	Send(*FileNode) error
	grpc.ServerStream
}

type analysisServiceGetSourceFileNodesServer struct {
	grpc.ServerStream
}

func (x *analysisServiceGetSourceFileNodesServer) Send(m *FileNode) error {
	return x.ServerStream.SendMsg(m)
}

var _AnalysisService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnalyzerConfig",
			Handler:    _AnalysisService_GetAnalyzerConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendInfoNodes",
			Handler:       _AnalysisService_SendInfoNodes_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendDiagnosticNode",
			Handler:       _AnalysisService_SendDiagnosticNode_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetSourceFileNodes",
			Handler:       _AnalysisService_GetSourceFileNodes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "analyzerservice.proto",
}
