// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controlservice.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogMessage struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogMessage) Reset()         { *m = LogMessage{} }
func (m *LogMessage) String() string { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()    {}
func (*LogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{0}
}

func (m *LogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMessage.Unmarshal(m, b)
}
func (m *LogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMessage.Marshal(b, m, deterministic)
}
func (m *LogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMessage.Merge(m, src)
}
func (m *LogMessage) XXX_Size() int {
	return xxx_messageInfo_LogMessage.Size(m)
}
func (m *LogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogMessage proto.InternalMessageInfo

func (m *LogMessage) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type LogResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogResponse) Reset()         { *m = LogResponse{} }
func (m *LogResponse) String() string { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()    {}
func (*LogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{1}
}

func (m *LogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponse.Unmarshal(m, b)
}
func (m *LogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponse.Marshal(b, m, deterministic)
}
func (m *LogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponse.Merge(m, src)
}
func (m *LogResponse) XXX_Size() int {
	return xxx_messageInfo_LogResponse.Size(m)
}
func (m *LogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponse proto.InternalMessageInfo

func (m *LogResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type QuitMessage struct {
	Kill                 bool     `protobuf:"varint,1,opt,name=kill,proto3" json:"kill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitMessage) Reset()         { *m = QuitMessage{} }
func (m *QuitMessage) String() string { return proto.CompactTextString(m) }
func (*QuitMessage) ProtoMessage()    {}
func (*QuitMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{2}
}

func (m *QuitMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitMessage.Unmarshal(m, b)
}
func (m *QuitMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitMessage.Marshal(b, m, deterministic)
}
func (m *QuitMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitMessage.Merge(m, src)
}
func (m *QuitMessage) XXX_Size() int {
	return xxx_messageInfo_QuitMessage.Size(m)
}
func (m *QuitMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitMessage.DiscardUnknown(m)
}

var xxx_messageInfo_QuitMessage proto.InternalMessageInfo

func (m *QuitMessage) GetKill() bool {
	if m != nil {
		return m.Kill
	}
	return false
}

type QuitResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitResponse) Reset()         { *m = QuitResponse{} }
func (m *QuitResponse) String() string { return proto.CompactTextString(m) }
func (*QuitResponse) ProtoMessage()    {}
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{3}
}

func (m *QuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitResponse.Unmarshal(m, b)
}
func (m *QuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitResponse.Marshal(b, m, deterministic)
}
func (m *QuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitResponse.Merge(m, src)
}
func (m *QuitResponse) XXX_Size() int {
	return xxx_messageInfo_QuitResponse.Size(m)
}
func (m *QuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitResponse proto.InternalMessageInfo

func (m *QuitResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SwitchPhaseMessage struct {
	Phase                Phase    `protobuf:"varint,1,opt,name=phase,proto3,enum=service.Phase" json:"phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchPhaseMessage) Reset()         { *m = SwitchPhaseMessage{} }
func (m *SwitchPhaseMessage) String() string { return proto.CompactTextString(m) }
func (*SwitchPhaseMessage) ProtoMessage()    {}
func (*SwitchPhaseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{4}
}

func (m *SwitchPhaseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchPhaseMessage.Unmarshal(m, b)
}
func (m *SwitchPhaseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchPhaseMessage.Marshal(b, m, deterministic)
}
func (m *SwitchPhaseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchPhaseMessage.Merge(m, src)
}
func (m *SwitchPhaseMessage) XXX_Size() int {
	return xxx_messageInfo_SwitchPhaseMessage.Size(m)
}
func (m *SwitchPhaseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchPhaseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchPhaseMessage proto.InternalMessageInfo

func (m *SwitchPhaseMessage) GetPhase() Phase {
	if m != nil {
		return m.Phase
	}
	return Phase_INIT
}

type SwitchPhaseResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	MasterConfig         string   `protobuf:"bytes,3,opt,name=masterConfig,proto3" json:"masterConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchPhaseResponse) Reset()         { *m = SwitchPhaseResponse{} }
func (m *SwitchPhaseResponse) String() string { return proto.CompactTextString(m) }
func (*SwitchPhaseResponse) ProtoMessage()    {}
func (*SwitchPhaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{5}
}

func (m *SwitchPhaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchPhaseResponse.Unmarshal(m, b)
}
func (m *SwitchPhaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchPhaseResponse.Marshal(b, m, deterministic)
}
func (m *SwitchPhaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchPhaseResponse.Merge(m, src)
}
func (m *SwitchPhaseResponse) XXX_Size() int {
	return xxx_messageInfo_SwitchPhaseResponse.Size(m)
}
func (m *SwitchPhaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchPhaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchPhaseResponse proto.InternalMessageInfo

func (m *SwitchPhaseResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SwitchPhaseResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SwitchPhaseResponse) GetMasterConfig() string {
	if m != nil {
		return m.MasterConfig
	}
	return ""
}

type GetFileNodeMessage struct {
	FileNode             *FileNode `protobuf:"bytes,1,opt,name=fileNode,proto3" json:"fileNode,omitempty"`
	UniqueNode           bool      `protobuf:"varint,2,opt,name=uniqueNode,proto3" json:"uniqueNode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetFileNodeMessage) Reset()         { *m = GetFileNodeMessage{} }
func (m *GetFileNodeMessage) String() string { return proto.CompactTextString(m) }
func (*GetFileNodeMessage) ProtoMessage()    {}
func (*GetFileNodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{6}
}

func (m *GetFileNodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileNodeMessage.Unmarshal(m, b)
}
func (m *GetFileNodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileNodeMessage.Marshal(b, m, deterministic)
}
func (m *GetFileNodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileNodeMessage.Merge(m, src)
}
func (m *GetFileNodeMessage) XXX_Size() int {
	return xxx_messageInfo_GetFileNodeMessage.Size(m)
}
func (m *GetFileNodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileNodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileNodeMessage proto.InternalMessageInfo

func (m *GetFileNodeMessage) GetFileNode() *FileNode {
	if m != nil {
		return m.FileNode
	}
	return nil
}

func (m *GetFileNodeMessage) GetUniqueNode() bool {
	if m != nil {
		return m.UniqueNode
	}
	return false
}

type StatusMessage struct {
	Phase                bool     `protobuf:"varint,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Switch               bool     `protobuf:"varint,2,opt,name=switch,proto3" json:"switch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusMessage) Reset()         { *m = StatusMessage{} }
func (m *StatusMessage) String() string { return proto.CompactTextString(m) }
func (*StatusMessage) ProtoMessage()    {}
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{7}
}

func (m *StatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMessage.Unmarshal(m, b)
}
func (m *StatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMessage.Marshal(b, m, deterministic)
}
func (m *StatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMessage.Merge(m, src)
}
func (m *StatusMessage) XXX_Size() int {
	return xxx_messageInfo_StatusMessage.Size(m)
}
func (m *StatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMessage proto.InternalMessageInfo

func (m *StatusMessage) GetPhase() bool {
	if m != nil {
		return m.Phase
	}
	return false
}

func (m *StatusMessage) GetSwitch() bool {
	if m != nil {
		return m.Switch
	}
	return false
}

type StatusResponse struct {
	Phase                string   `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	PhaseID              Phase    `protobuf:"varint,2,opt,name=phaseID,proto3,enum=service.Phase" json:"phaseID,omitempty"`
	Switching            bool     `protobuf:"varint,3,opt,name=switching,proto3" json:"switching,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	PendingInserts       uint64   `protobuf:"varint,5,opt,name=pendingInserts,proto3" json:"pendingInserts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{8}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func (m *StatusResponse) GetPhaseID() Phase {
	if m != nil {
		return m.PhaseID
	}
	return Phase_INIT
}

func (m *StatusResponse) GetSwitching() bool {
	if m != nil {
		return m.Switching
	}
	return false
}

func (m *StatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *StatusResponse) GetPendingInserts() uint64 {
	if m != nil {
		return m.PendingInserts
	}
	return 0
}

type EventMessage struct {
	Class                EventClass `protobuf:"varint,1,opt,name=class,proto3,enum=service.EventClass" json:"class,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EventMessage) Reset()         { *m = EventMessage{} }
func (m *EventMessage) String() string { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()    {}
func (*EventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{9}
}

func (m *EventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMessage.Unmarshal(m, b)
}
func (m *EventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMessage.Marshal(b, m, deterministic)
}
func (m *EventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMessage.Merge(m, src)
}
func (m *EventMessage) XXX_Size() int {
	return xxx_messageInfo_EventMessage.Size(m)
}
func (m *EventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventMessage proto.InternalMessageInfo

func (m *EventMessage) GetClass() EventClass {
	if m != nil {
		return m.Class
	}
	return EventClass_ALL
}

type ExportRequest struct {
	Wait                 bool     `protobuf:"varint,1,opt,name=wait,proto3" json:"wait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportRequest) Reset()         { *m = ExportRequest{} }
func (m *ExportRequest) String() string { return proto.CompactTextString(m) }
func (*ExportRequest) ProtoMessage()    {}
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{10}
}

func (m *ExportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportRequest.Unmarshal(m, b)
}
func (m *ExportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportRequest.Marshal(b, m, deterministic)
}
func (m *ExportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportRequest.Merge(m, src)
}
func (m *ExportRequest) XXX_Size() int {
	return xxx_messageInfo_ExportRequest.Size(m)
}
func (m *ExportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExportRequest proto.InternalMessageInfo

func (m *ExportRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

type ExportResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportResponse) Reset()         { *m = ExportResponse{} }
func (m *ExportResponse) String() string { return proto.CompactTextString(m) }
func (*ExportResponse) ProtoMessage()    {}
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{11}
}

func (m *ExportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportResponse.Unmarshal(m, b)
}
func (m *ExportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportResponse.Marshal(b, m, deterministic)
}
func (m *ExportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportResponse.Merge(m, src)
}
func (m *ExportResponse) XXX_Size() int {
	return xxx_messageInfo_ExportResponse.Size(m)
}
func (m *ExportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExportResponse proto.InternalMessageInfo

func (m *ExportResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type InitModuleRequest struct {
	ModuleName           string   `protobuf:"bytes,1,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	ExtraConfig          int64    `protobuf:"varint,2,opt,name=extraConfig,proto3" json:"extraConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitModuleRequest) Reset()         { *m = InitModuleRequest{} }
func (m *InitModuleRequest) String() string { return proto.CompactTextString(m) }
func (*InitModuleRequest) ProtoMessage()    {}
func (*InitModuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{12}
}

func (m *InitModuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitModuleRequest.Unmarshal(m, b)
}
func (m *InitModuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitModuleRequest.Marshal(b, m, deterministic)
}
func (m *InitModuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitModuleRequest.Merge(m, src)
}
func (m *InitModuleRequest) XXX_Size() int {
	return xxx_messageInfo_InitModuleRequest.Size(m)
}
func (m *InitModuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitModuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitModuleRequest proto.InternalMessageInfo

func (m *InitModuleRequest) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *InitModuleRequest) GetExtraConfig() int64 {
	if m != nil {
		return m.ExtraConfig
	}
	return 0
}

type InitModuleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitModuleResponse) Reset()         { *m = InitModuleResponse{} }
func (m *InitModuleResponse) String() string { return proto.CompactTextString(m) }
func (*InitModuleResponse) ProtoMessage()    {}
func (*InitModuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{13}
}

func (m *InitModuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitModuleResponse.Unmarshal(m, b)
}
func (m *InitModuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitModuleResponse.Marshal(b, m, deterministic)
}
func (m *InitModuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitModuleResponse.Merge(m, src)
}
func (m *InitModuleResponse) XXX_Size() int {
	return xxx_messageInfo_InitModuleResponse.Size(m)
}
func (m *InitModuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitModuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitModuleResponse proto.InternalMessageInfo

type ShutdownModuleRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DB                   bool     `protobuf:"varint,2,opt,name=dB,proto3" json:"dB,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownModuleRequest) Reset()         { *m = ShutdownModuleRequest{} }
func (m *ShutdownModuleRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownModuleRequest) ProtoMessage()    {}
func (*ShutdownModuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{14}
}

func (m *ShutdownModuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownModuleRequest.Unmarshal(m, b)
}
func (m *ShutdownModuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownModuleRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownModuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownModuleRequest.Merge(m, src)
}
func (m *ShutdownModuleRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownModuleRequest.Size(m)
}
func (m *ShutdownModuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownModuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownModuleRequest proto.InternalMessageInfo

func (m *ShutdownModuleRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ShutdownModuleRequest) GetDB() bool {
	if m != nil {
		return m.DB
	}
	return false
}

type ShutdownModuleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownModuleResponse) Reset()         { *m = ShutdownModuleResponse{} }
func (m *ShutdownModuleResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownModuleResponse) ProtoMessage()    {}
func (*ShutdownModuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_931c7f2b376aa187, []int{15}
}

func (m *ShutdownModuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownModuleResponse.Unmarshal(m, b)
}
func (m *ShutdownModuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownModuleResponse.Marshal(b, m, deterministic)
}
func (m *ShutdownModuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownModuleResponse.Merge(m, src)
}
func (m *ShutdownModuleResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownModuleResponse.Size(m)
}
func (m *ShutdownModuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownModuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownModuleResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LogMessage)(nil), "service.LogMessage")
	proto.RegisterType((*LogResponse)(nil), "service.LogResponse")
	proto.RegisterType((*QuitMessage)(nil), "service.QuitMessage")
	proto.RegisterType((*QuitResponse)(nil), "service.QuitResponse")
	proto.RegisterType((*SwitchPhaseMessage)(nil), "service.SwitchPhaseMessage")
	proto.RegisterType((*SwitchPhaseResponse)(nil), "service.SwitchPhaseResponse")
	proto.RegisterType((*GetFileNodeMessage)(nil), "service.GetFileNodeMessage")
	proto.RegisterType((*StatusMessage)(nil), "service.StatusMessage")
	proto.RegisterType((*StatusResponse)(nil), "service.StatusResponse")
	proto.RegisterType((*EventMessage)(nil), "service.EventMessage")
	proto.RegisterType((*ExportRequest)(nil), "service.ExportRequest")
	proto.RegisterType((*ExportResponse)(nil), "service.ExportResponse")
	proto.RegisterType((*InitModuleRequest)(nil), "service.InitModuleRequest")
	proto.RegisterType((*InitModuleResponse)(nil), "service.InitModuleResponse")
	proto.RegisterType((*ShutdownModuleRequest)(nil), "service.ShutdownModuleRequest")
	proto.RegisterType((*ShutdownModuleResponse)(nil), "service.ShutdownModuleResponse")
}

func init() { proto.RegisterFile("controlservice.proto", fileDescriptor_931c7f2b376aa187) }

var fileDescriptor_931c7f2b376aa187 = []byte{
	// 759 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdf, 0x4f, 0xdb, 0x3a,
	0x14, 0xee, 0xef, 0x96, 0xd3, 0x12, 0x2e, 0xa6, 0xf4, 0x46, 0x01, 0xf5, 0xf6, 0xfa, 0x5e, 0x6d,
	0xdd, 0xa4, 0x55, 0x53, 0xa7, 0x3d, 0xec, 0x97, 0x04, 0x14, 0x86, 0x3a, 0x01, 0x62, 0xe9, 0x26,
	0xed, 0x35, 0x24, 0x26, 0x8d, 0x68, 0xe3, 0x12, 0x3b, 0xc0, 0x1f, 0xb5, 0xf7, 0xfd, 0x7b, 0x53,
	0x9c, 0x38, 0x71, 0x68, 0x2b, 0xf6, 0x66, 0x7f, 0xe7, 0xf3, 0x77, 0x4e, 0x3e, 0xfb, 0x9c, 0x40,
	0xdb, 0xa6, 0x3e, 0x0f, 0xe8, 0x8c, 0x91, 0xe0, 0xce, 0xb3, 0xc9, 0x60, 0x11, 0x50, 0x4e, 0x51,
	0x3d, 0xd9, 0x1a, 0x5b, 0x8e, 0xc5, 0xad, 0x39, 0x75, 0xc8, 0x2c, 0x8e, 0xe0, 0x2e, 0xc0, 0x19,
	0x75, 0xcf, 0x09, 0x63, 0x96, 0x4b, 0xd0, 0x5f, 0x50, 0x9e, 0x33, 0x57, 0x2f, 0xf6, 0x8a, 0xfd,
	0x96, 0x19, 0x2d, 0xf1, 0x73, 0x68, 0x9e, 0x51, 0xd7, 0x24, 0x6c, 0x41, 0x7d, 0x46, 0x90, 0x0e,
	0x75, 0x16, 0xda, 0x36, 0x61, 0x4c, 0x90, 0x1a, 0xa6, 0xdc, 0xe2, 0x7f, 0xa1, 0xf9, 0x35, 0xf4,
	0xb8, 0x54, 0x42, 0x50, 0xb9, 0xf1, 0x66, 0xb3, 0x84, 0x25, 0xd6, 0xb8, 0x0f, 0xad, 0x88, 0xf2,
	0x07, 0x62, 0xef, 0x01, 0x4d, 0xee, 0x3d, 0x6e, 0x4f, 0x2f, 0xa7, 0x16, 0x23, 0x52, 0xf3, 0x7f,
	0xa8, 0x2e, 0xa2, 0xbd, 0x60, 0x6b, 0x43, 0x6d, 0x20, 0x3f, 0x52, 0xb0, 0xcc, 0x38, 0x88, 0x3d,
	0xd8, 0x51, 0xce, 0x3e, 0x9d, 0x0c, 0xb5, 0xa1, 0x4a, 0x82, 0x80, 0x06, 0x7a, 0xa9, 0x57, 0xec,
	0x6f, 0x98, 0xf1, 0x06, 0x61, 0x68, 0xcd, 0x2d, 0xc6, 0x49, 0x30, 0xa2, 0xfe, 0xb5, 0xe7, 0xea,
	0x65, 0x11, 0xcc, 0x61, 0xd8, 0x06, 0x74, 0x4a, 0xf8, 0x67, 0x6f, 0x46, 0x2e, 0xa8, 0x93, 0x96,
	0xf9, 0x0a, 0x1a, 0xd7, 0x09, 0x24, 0x52, 0x35, 0x87, 0xdb, 0x69, 0xa5, 0x92, 0x6b, 0xa6, 0x14,
	0xd4, 0x05, 0x08, 0x7d, 0xef, 0x36, 0x8c, 0x0f, 0x94, 0x44, 0x6d, 0x0a, 0x82, 0x3f, 0xc1, 0xe6,
	0x84, 0x5b, 0x3c, 0x64, 0x52, 0xbf, 0xad, 0xda, 0xd0, 0x48, 0x3e, 0x1b, 0x75, 0xa0, 0xc6, 0xc4,
	0x67, 0x27, 0x12, 0xc9, 0x0e, 0xff, 0x2c, 0x82, 0x16, 0x9f, 0x4f, 0xad, 0xc8, 0x09, 0x6c, 0x48,
	0x81, 0x3e, 0xd4, 0xc5, 0x62, 0x7c, 0x2c, 0x14, 0x96, 0xfd, 0x95, 0x61, 0xb4, 0x0f, 0x1b, 0xb1,
	0xb8, 0xe7, 0xc7, 0xbe, 0x34, 0xcc, 0x0c, 0xc8, 0xec, 0xac, 0xa8, 0x76, 0x3e, 0x03, 0x6d, 0x41,
	0x7c, 0xc7, 0xf3, 0xdd, 0xb1, 0xcf, 0x48, 0xc0, 0x99, 0x5e, 0xed, 0x15, 0xfb, 0x15, 0xf3, 0x11,
	0x8a, 0xdf, 0x41, 0xeb, 0xe4, 0x8e, 0xf8, 0xe9, 0x3b, 0x7a, 0x01, 0x55, 0x7b, 0x66, 0x25, 0x97,
	0xa6, 0x0d, 0x77, 0xd2, 0x9a, 0x04, 0x6b, 0x14, 0x85, 0xcc, 0x98, 0x81, 0xff, 0x83, 0xcd, 0x93,
	0x87, 0x05, 0x0d, 0xb8, 0x49, 0x6e, 0x43, 0xc2, 0x78, 0xf4, 0x06, 0xef, 0x2d, 0x8f, 0xcb, 0x37,
	0x18, 0xad, 0xf1, 0x4b, 0xd0, 0x24, 0xe9, 0xc9, 0x57, 0xf8, 0x1d, 0xb6, 0xc7, 0xbe, 0xc7, 0xcf,
	0xa9, 0x13, 0xce, 0x88, 0x14, 0xed, 0x02, 0xcc, 0x05, 0x70, 0x61, 0xcd, 0xa5, 0x83, 0x0a, 0x82,
	0x7a, 0xd0, 0x24, 0x0f, 0x3c, 0xb0, 0x92, 0x67, 0x13, 0x59, 0x59, 0x36, 0x55, 0x08, 0xb7, 0x01,
	0xa9, 0xb2, 0x71, 0x19, 0xf8, 0x10, 0x76, 0x27, 0xd3, 0x90, 0x3b, 0xf4, 0xde, 0xcf, 0x27, 0xd4,
	0xa1, 0x3e, 0x8f, 0xcd, 0x48, 0xb2, 0xc9, 0x2d, 0xd2, 0xa0, 0xe4, 0x1c, 0x25, 0xd7, 0x5d, 0x72,
	0x8e, 0xb0, 0x0e, 0x9d, 0xc7, 0x12, 0xb1, 0xf8, 0xf0, 0x57, 0x0d, 0xb4, 0x51, 0x3c, 0x18, 0x26,
	0xb1, 0x7f, 0x68, 0x08, 0xe5, 0x33, 0xea, 0xa2, 0xcc, 0xd0, 0x6c, 0x0c, 0x18, 0x6d, 0x15, 0x4c,
	0x2b, 0x2c, 0xa0, 0xb7, 0x50, 0x89, 0x1a, 0x18, 0x65, 0x71, 0xa5, 0xe5, 0x8d, 0xdd, 0x1c, 0xaa,
	0x1c, 0xfb, 0x02, 0x4d, 0xa5, 0x23, 0xd1, 0x5e, 0xca, 0x5b, 0xee, 0x71, 0x63, 0x7f, 0x55, 0x50,
	0xd1, 0x3a, 0x05, 0xc8, 0xcc, 0x43, 0x46, 0xca, 0x5e, 0xba, 0x28, 0x63, 0x6f, 0x65, 0x2c, 0x15,
	0x9a, 0x80, 0x96, 0x37, 0x0b, 0x75, 0xb3, 0xd4, 0xab, 0x2e, 0xc2, 0xf8, 0x67, 0x6d, 0x3c, 0x15,
	0x3d, 0x00, 0xed, 0x94, 0xf0, 0x4b, 0xcb, 0xbe, 0xb1, 0xdc, 0xb8, 0xbb, 0x33, 0xab, 0x14, 0xd4,
	0x58, 0x89, 0xe2, 0xc2, 0xeb, 0x22, 0x3a, 0x80, 0xed, 0x4c, 0xe1, 0x9b, 0x15, 0xb8, 0x84, 0xb3,
	0x35, 0x22, 0xcb, 0x53, 0x45, 0x28, 0x1c, 0x42, 0x53, 0x19, 0x4a, 0x8a, 0xdb, 0xcb, 0xa3, 0x6a,
	0x9d, 0xc4, 0x58, 0x14, 0x71, 0xec, 0x59, 0xae, 0x4f, 0x19, 0xf7, 0x6c, 0x21, 0xf4, 0x77, 0xca,
	0xcd, 0x07, 0x8c, 0x75, 0x01, 0x21, 0xf5, 0x01, 0x6a, 0xf1, 0xf4, 0x41, 0x9d, 0xcc, 0x3e, 0x75,
	0x9c, 0x29, 0xc7, 0xf3, 0x63, 0x0a, 0x17, 0xd0, 0x47, 0xd8, 0x9a, 0x84, 0x57, 0xcc, 0x0e, 0xbc,
	0x2b, 0x22, 0xfa, 0x9d, 0xa1, 0xdd, 0xfc, 0x00, 0x90, 0x22, 0x5a, 0x1e, 0x16, 0xa9, 0x47, 0xb2,
	0xd5, 0x27, 0xbe, 0xb5, 0x60, 0x53, 0xca, 0x95, 0x12, 0x72, 0x83, 0x42, 0x29, 0x21, 0x3f, 0x1b,
	0x70, 0xe1, 0x48, 0x87, 0x0e, 0x0d, 0xdc, 0xc1, 0xed, 0x9c, 0xf1, 0x60, 0xe0, 0x06, 0x0b, 0x5b,
	0x52, 0x7f, 0x14, 0xae, 0x6a, 0xe2, 0x17, 0xfa, 0xe6, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a,
	0x04, 0xf3, 0x70, 0x74, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlServiceClient interface {
	Log(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error)
	Quit(ctx context.Context, in *QuitMessage, opts ...grpc.CallOption) (*QuitResponse, error)
	SwitchPhase(ctx context.Context, in *SwitchPhaseMessage, opts ...grpc.CallOption) (*SwitchPhaseResponse, error)
	InitModule(ctx context.Context, in *InitModuleRequest, opts ...grpc.CallOption) (*InitModuleResponse, error)
	ShutdownModule(ctx context.Context, in *ShutdownModuleRequest, opts ...grpc.CallOption) (*ShutdownModuleResponse, error)
	GetPackageNode(ctx context.Context, in *PackageNode, opts ...grpc.CallOption) (ControlService_GetPackageNodeClient, error)
	GetPackageTargets(ctx context.Context, in *PackageNode, opts ...grpc.CallOption) (ControlService_GetPackageTargetsClient, error)
	GetFileNode(ctx context.Context, in *GetFileNodeMessage, opts ...grpc.CallOption) (ControlService_GetFileNodeClient, error)
	GetDiagnosticNode(ctx context.Context, in *DiagnosticNode, opts ...grpc.CallOption) (ControlService_GetDiagnosticNodeClient, error)
	Status(ctx context.Context, in *StatusMessage, opts ...grpc.CallOption) (*StatusResponse, error)
	SubscribeEvents(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (ControlService_SubscribeEventsClient, error)
	ExportSnapshot(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
}

type controlServiceClient struct {
	cc *grpc.ClientConn
}

func NewControlServiceClient(cc *grpc.ClientConn) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) Log(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/service.ControlService/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Quit(ctx context.Context, in *QuitMessage, opts ...grpc.CallOption) (*QuitResponse, error) {
	out := new(QuitResponse)
	err := c.cc.Invoke(ctx, "/service.ControlService/Quit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SwitchPhase(ctx context.Context, in *SwitchPhaseMessage, opts ...grpc.CallOption) (*SwitchPhaseResponse, error) {
	out := new(SwitchPhaseResponse)
	err := c.cc.Invoke(ctx, "/service.ControlService/SwitchPhase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) InitModule(ctx context.Context, in *InitModuleRequest, opts ...grpc.CallOption) (*InitModuleResponse, error) {
	out := new(InitModuleResponse)
	err := c.cc.Invoke(ctx, "/service.ControlService/InitModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ShutdownModule(ctx context.Context, in *ShutdownModuleRequest, opts ...grpc.CallOption) (*ShutdownModuleResponse, error) {
	out := new(ShutdownModuleResponse)
	err := c.cc.Invoke(ctx, "/service.ControlService/ShutdownModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetPackageNode(ctx context.Context, in *PackageNode, opts ...grpc.CallOption) (ControlService_GetPackageNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControlService_serviceDesc.Streams[0], "/service.ControlService/GetPackageNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServiceGetPackageNodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlService_GetPackageNodeClient interface {
	Recv() (*PackageNode, error)
	grpc.ClientStream
}

type controlServiceGetPackageNodeClient struct {
	grpc.ClientStream
}

func (x *controlServiceGetPackageNodeClient) Recv() (*PackageNode, error) {
	m := new(PackageNode)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlServiceClient) GetPackageTargets(ctx context.Context, in *PackageNode, opts ...grpc.CallOption) (ControlService_GetPackageTargetsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControlService_serviceDesc.Streams[1], "/service.ControlService/GetPackageTargets", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServiceGetPackageTargetsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlService_GetPackageTargetsClient interface {
	Recv() (*FileNode, error)
	grpc.ClientStream
}

type controlServiceGetPackageTargetsClient struct {
	grpc.ClientStream
}

func (x *controlServiceGetPackageTargetsClient) Recv() (*FileNode, error) {
	m := new(FileNode)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlServiceClient) GetFileNode(ctx context.Context, in *GetFileNodeMessage, opts ...grpc.CallOption) (ControlService_GetFileNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControlService_serviceDesc.Streams[2], "/service.ControlService/GetFileNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServiceGetFileNodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlService_GetFileNodeClient interface {
	Recv() (*FileNode, error)
	grpc.ClientStream
}

type controlServiceGetFileNodeClient struct {
	grpc.ClientStream
}

func (x *controlServiceGetFileNodeClient) Recv() (*FileNode, error) {
	m := new(FileNode)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlServiceClient) GetDiagnosticNode(ctx context.Context, in *DiagnosticNode, opts ...grpc.CallOption) (ControlService_GetDiagnosticNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControlService_serviceDesc.Streams[3], "/service.ControlService/GetDiagnosticNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServiceGetDiagnosticNodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlService_GetDiagnosticNodeClient interface {
	Recv() (*DiagnosticNode, error)
	grpc.ClientStream
}

type controlServiceGetDiagnosticNodeClient struct {
	grpc.ClientStream
}

func (x *controlServiceGetDiagnosticNodeClient) Recv() (*DiagnosticNode, error) {
	m := new(DiagnosticNode)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlServiceClient) Status(ctx context.Context, in *StatusMessage, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/service.ControlService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SubscribeEvents(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (ControlService_SubscribeEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControlService_serviceDesc.Streams[4], "/service.ControlService/SubscribeEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServiceSubscribeEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlService_SubscribeEventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type controlServiceSubscribeEventsClient struct {
	grpc.ClientStream
}

func (x *controlServiceSubscribeEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlServiceClient) ExportSnapshot(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, "/service.ControlService/ExportSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
type ControlServiceServer interface {
	Log(context.Context, *LogMessage) (*LogResponse, error)
	Quit(context.Context, *QuitMessage) (*QuitResponse, error)
	SwitchPhase(context.Context, *SwitchPhaseMessage) (*SwitchPhaseResponse, error)
	InitModule(context.Context, *InitModuleRequest) (*InitModuleResponse, error)
	ShutdownModule(context.Context, *ShutdownModuleRequest) (*ShutdownModuleResponse, error)
	GetPackageNode(*PackageNode, ControlService_GetPackageNodeServer) error
	GetPackageTargets(*PackageNode, ControlService_GetPackageTargetsServer) error
	GetFileNode(*GetFileNodeMessage, ControlService_GetFileNodeServer) error
	GetDiagnosticNode(*DiagnosticNode, ControlService_GetDiagnosticNodeServer) error
	Status(context.Context, *StatusMessage) (*StatusResponse, error)
	SubscribeEvents(*EventMessage, ControlService_SubscribeEventsServer) error
	ExportSnapshot(context.Context, *ExportRequest) (*ExportResponse, error)
}

// UnimplementedControlServiceServer can be embedded to have forward compatible implementations.
type UnimplementedControlServiceServer struct {
}

func (*UnimplementedControlServiceServer) Log(ctx context.Context, req *LogMessage) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (*UnimplementedControlServiceServer) Quit(ctx context.Context, req *QuitMessage) (*QuitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quit not implemented")
}
func (*UnimplementedControlServiceServer) SwitchPhase(ctx context.Context, req *SwitchPhaseMessage) (*SwitchPhaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchPhase not implemented")
}
func (*UnimplementedControlServiceServer) InitModule(ctx context.Context, req *InitModuleRequest) (*InitModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitModule not implemented")
}
func (*UnimplementedControlServiceServer) ShutdownModule(ctx context.Context, req *ShutdownModuleRequest) (*ShutdownModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutdownModule not implemented")
}
func (*UnimplementedControlServiceServer) GetPackageNode(req *PackageNode, srv ControlService_GetPackageNodeServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPackageNode not implemented")
}
func (*UnimplementedControlServiceServer) GetPackageTargets(req *PackageNode, srv ControlService_GetPackageTargetsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPackageTargets not implemented")
}
func (*UnimplementedControlServiceServer) GetFileNode(req *GetFileNodeMessage, srv ControlService_GetFileNodeServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFileNode not implemented")
}
func (*UnimplementedControlServiceServer) GetDiagnosticNode(req *DiagnosticNode, srv ControlService_GetDiagnosticNodeServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDiagnosticNode not implemented")
}
func (*UnimplementedControlServiceServer) Status(ctx context.Context, req *StatusMessage) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedControlServiceServer) SubscribeEvents(req *EventMessage, srv ControlService_SubscribeEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (*UnimplementedControlServiceServer) ExportSnapshot(ctx context.Context, req *ExportRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportSnapshot not implemented")
}

func RegisterControlServiceServer(s *grpc.Server, srv ControlServiceServer) {
	s.RegisterService(&_ControlService_serviceDesc, srv)
}

func _ControlService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ControlService/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Log(ctx, req.(*LogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ControlService/Quit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Quit(ctx, req.(*QuitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SwitchPhase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchPhaseMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SwitchPhase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ControlService/SwitchPhase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SwitchPhase(ctx, req.(*SwitchPhaseMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_InitModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).InitModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ControlService/InitModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).InitModule(ctx, req.(*InitModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ShutdownModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ShutdownModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ControlService/ShutdownModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ShutdownModule(ctx, req.(*ShutdownModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetPackageNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageNode)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).GetPackageNode(m, &controlServiceGetPackageNodeServer{stream})
}

type ControlService_GetPackageNodeServer interface {
	Send(*PackageNode) error
	grpc.ServerStream
}

type controlServiceGetPackageNodeServer struct {
	grpc.ServerStream
}

func (x *controlServiceGetPackageNodeServer) Send(m *PackageNode) error {
	return x.ServerStream.SendMsg(m)
}

func _ControlService_GetPackageTargets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageNode)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).GetPackageTargets(m, &controlServiceGetPackageTargetsServer{stream})
}

type ControlService_GetPackageTargetsServer interface {
	Send(*FileNode) error
	grpc.ServerStream
}

type controlServiceGetPackageTargetsServer struct {
	grpc.ServerStream
}

func (x *controlServiceGetPackageTargetsServer) Send(m *FileNode) error {
	return x.ServerStream.SendMsg(m)
}

func _ControlService_GetFileNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileNodeMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).GetFileNode(m, &controlServiceGetFileNodeServer{stream})
}

type ControlService_GetFileNodeServer interface {
	Send(*FileNode) error
	grpc.ServerStream
}

type controlServiceGetFileNodeServer struct {
	grpc.ServerStream
}

func (x *controlServiceGetFileNodeServer) Send(m *FileNode) error {
	return x.ServerStream.SendMsg(m)
}

func _ControlService_GetDiagnosticNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DiagnosticNode)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).GetDiagnosticNode(m, &controlServiceGetDiagnosticNodeServer{stream})
}

type ControlService_GetDiagnosticNodeServer interface {
	Send(*DiagnosticNode) error
	grpc.ServerStream
}

type controlServiceGetDiagnosticNodeServer struct {
	grpc.ServerStream
}

func (x *controlServiceGetDiagnosticNodeServer) Send(m *DiagnosticNode) error {
	return x.ServerStream.SendMsg(m)
}

func _ControlService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ControlService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Status(ctx, req.(*StatusMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).SubscribeEvents(m, &controlServiceSubscribeEventsServer{stream})
}

type ControlService_SubscribeEventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type controlServiceSubscribeEventsServer struct {
	grpc.ServerStream
}

func (x *controlServiceSubscribeEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _ControlService_ExportSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ExportSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ControlService/ExportSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ExportSnapshot(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _ControlService_Log_Handler,
		},
		{
			MethodName: "Quit",
			Handler:    _ControlService_Quit_Handler,
		},
		{
			MethodName: "SwitchPhase",
			Handler:    _ControlService_SwitchPhase_Handler,
		},
		{
			MethodName: "InitModule",
			Handler:    _ControlService_InitModule_Handler,
		},
		{
			MethodName: "ShutdownModule",
			Handler:    _ControlService_ShutdownModule_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _ControlService_Status_Handler,
		},
		{
			MethodName: "ExportSnapshot",
			Handler:    _ControlService_ExportSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPackageNode",
			Handler:       _ControlService_GetPackageNode_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPackageTargets",
			Handler:       _ControlService_GetPackageTargets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetFileNode",
			Handler:       _ControlService_GetFileNode_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDiagnosticNode",
			Handler:       _ControlService_GetDiagnosticNode_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeEvents",
			Handler:       _ControlService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controlservice.proto",
}
