QMSTR_WRAPPER_BUILDER := qmstr-wrapper

.PHONY: $(QMSTR_WRAPPER_BUILDER)
$(QMSTR_WRAPPER_BUILDER): $(OUTDIR)builders/$(QMSTR_WRAPPER_BUILDER)

$(OUTDIR)builders/$(QMSTR_WRAPPER_BUILDER): $(GO_SRCS)
	go test github.com/QMSTR/qmstr/modules/$(subst $(OUTDIR),,$@)
	go build -o $@ github.com/QMSTR/qmstr/modules/$(subst $(OUTDIR),,$@)