QMSTR-HTML_REPORTER := qmstr-reporter-html

.PHONY: $(QMSTR-HTML_REPORTER)
$(QMSTR-HTML_REPORTER): $(OUTDIR)reporters/$(QMSTR-HTML_REPORTER)

$(OUTDIR)reporters/$(QMSTR-HTML_REPORTER): $(GO_SRCS)
	go test github.com/QMSTR/qmstr/modules/$(subst $(OUTDIR),,$@)
	go build -o $@ github.com/QMSTR/qmstr/modules/$(subst $(OUTDIR),,$@)