QMSTR-HTML_REPORTER := qmstr-reporter-html

.PHONY: $(QMSTR-HTML_REPORTER)
$(QMSTR-HTML_REPORTER): $(OUTDIR)reporters/$(QMSTR-HTML_REPORTER)

$(OUTDIR)reporters/$(QMSTR-HTML_REPORTER): $(GO_SRCS)
	go test ./modules/$(subst $(OUTDIR),,$@)
	go build -o $@ ./modules/$(subst $(OUTDIR),,$@)