apiVersion: v1
kind: Service
metadata:
  name: dgraph
  labels:
    app: qmstr
spec:
  type: ClusterIP
  selector:
    app: qmstr
  ports:
    - name: grpc-zero
      port: 5080
      targetPort: 5080
    - name: http-zero
      port: 6080
      targetPort: 6080
    - name: http-alpha
      port: 8080
      targetPort: 8080
    - name: grpc-alpha
      port: 9080
      targetPort: 9080
    - name: http-ratel
      port: 8000
      targetPort: 8000
