SCANCODE_ANALYZER := scancode-analyzer

.PHONY: $(SCANCODE_ANALYZER)
$(SCANCODE_ANALYZER): $(OUTDIR)analyzers/$(SCANCODE_ANALYZER)

$(OUTDIR)analyzers/$(SCANCODE_ANALYZER): $(GO_SRCS)
	go test github.com/QMSTR/qmstr/modules/$(subst $(OUTDIR),,$@)
	go build -o $@ github.com/QMSTR/qmstr/modules/$(subst $(OUTDIR),,$@)