SPDX_ANALYZER := spdx-analyzer

.PHONY: $(SPDX_ANALYZER)
$(SPDX_ANALYZER): $(OUTDIR)analyzers/$(SPDX_ANALYZER)

$(OUTDIR)analyzers/$(SPDX_ANALYZER): venv/bin/pex pyqmstr
	QMSTR_VERSION=$(QMSTR_VERSION) venv/bin/pex modules/analyzers/$(SPDX_ANALYZER) pyqmstr -e spdxanalyzer.__main__:main --python=venv/bin/python3 --disable-cache -f ./out/wheels -o $@