PY_BUILDER := qmstr-py-builder

.PHONY: $(PY_BUILDER)
$(PY_BUILDER): venv
	QMSTR_VERSION=$(QMSTR_VERSION) venv/bin/pip install lib/pyqmstr
	QMSTR_VERSION=$(QMSTR_VERSION) venv/bin/pip install modules/builders/$(PY_BUILDER)
