# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyzerservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import datamodel_pb2 as datamodel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='analyzerservice.proto',
  package='service',
  syntax='proto3',
  serialized_options=_b('\n\026org.qmstr.grpc.service'),
  serialized_pb=_b('\n\x15\x61nalyzerservice.proto\x12\x07service\x1a\x0f\x64\x61tamodel.proto\"+\n\x15\x41nalyzerConfigRequest\x12\x12\n\nanalyzerID\x18\x01 \x01(\x05\"?\n\x16\x41nalyzerConfigResponse\x12\x16\n\x0e\x61nalyzerConfig\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\x03\"T\n\x10InfoNodesMessage\x12\r\n\x05token\x18\x01 \x01(\x03\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12$\n\tinfonodes\x18\x03 \x03(\x0b\x32\x11.service.InfoNode\"d\n\x15\x44iagnosticNodeMessage\x12\r\n\x05token\x18\x01 \x01(\x03\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12/\n\x0e\x64iagnosticnode\x18\x03 \x01(\x0b\x32\x17.service.DiagnosticNode\"\x1f\n\x0cSendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x0e\n\x0c\x44ummyRequest2\xc5\x02\n\x0f\x41nalysisService\x12V\n\x11GetAnalyzerConfig\x12\x1e.service.AnalyzerConfigRequest\x1a\x1f.service.AnalyzerConfigResponse\"\x00\x12\x45\n\rSendInfoNodes\x12\x19.service.InfoNodesMessage\x1a\x15.service.SendResponse\"\x00(\x01\x12O\n\x12SendDiagnosticNode\x12\x1e.service.DiagnosticNodeMessage\x1a\x15.service.SendResponse\"\x00(\x01\x12\x42\n\x12GetSourceFileNodes\x12\x15.service.DummyRequest\x1a\x11.service.FileNode\"\x00\x30\x01\x42\x18\n\x16org.qmstr.grpc.serviceX\x00\x62\x06proto3')
  ,
  dependencies=[datamodel__pb2.DESCRIPTOR,])




_ANALYZERCONFIGREQUEST = _descriptor.Descriptor(
  name='AnalyzerConfigRequest',
  full_name='service.AnalyzerConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='analyzerID', full_name='service.AnalyzerConfigRequest.analyzerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=94,
)


_ANALYZERCONFIGRESPONSE = _descriptor.Descriptor(
  name='AnalyzerConfigResponse',
  full_name='service.AnalyzerConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='analyzerConfig', full_name='service.AnalyzerConfigResponse.analyzerConfig', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='service.AnalyzerConfigResponse.token', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=159,
)


_INFONODESMESSAGE = _descriptor.Descriptor(
  name='InfoNodesMessage',
  full_name='service.InfoNodesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='service.InfoNodesMessage.token', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='service.InfoNodesMessage.uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infonodes', full_name='service.InfoNodesMessage.infonodes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=245,
)


_DIAGNOSTICNODEMESSAGE = _descriptor.Descriptor(
  name='DiagnosticNodeMessage',
  full_name='service.DiagnosticNodeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='service.DiagnosticNodeMessage.token', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='service.DiagnosticNodeMessage.uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagnosticnode', full_name='service.DiagnosticNodeMessage.diagnosticnode', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=347,
)


_SENDRESPONSE = _descriptor.Descriptor(
  name='SendResponse',
  full_name='service.SendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='service.SendResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=380,
)


_DUMMYREQUEST = _descriptor.Descriptor(
  name='DummyRequest',
  full_name='service.DummyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=396,
)

_INFONODESMESSAGE.fields_by_name['infonodes'].message_type = datamodel__pb2._INFONODE
_DIAGNOSTICNODEMESSAGE.fields_by_name['diagnosticnode'].message_type = datamodel__pb2._DIAGNOSTICNODE
DESCRIPTOR.message_types_by_name['AnalyzerConfigRequest'] = _ANALYZERCONFIGREQUEST
DESCRIPTOR.message_types_by_name['AnalyzerConfigResponse'] = _ANALYZERCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['InfoNodesMessage'] = _INFONODESMESSAGE
DESCRIPTOR.message_types_by_name['DiagnosticNodeMessage'] = _DIAGNOSTICNODEMESSAGE
DESCRIPTOR.message_types_by_name['SendResponse'] = _SENDRESPONSE
DESCRIPTOR.message_types_by_name['DummyRequest'] = _DUMMYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalyzerConfigRequest = _reflection.GeneratedProtocolMessageType('AnalyzerConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _ANALYZERCONFIGREQUEST,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.AnalyzerConfigRequest)
  ))
_sym_db.RegisterMessage(AnalyzerConfigRequest)

AnalyzerConfigResponse = _reflection.GeneratedProtocolMessageType('AnalyzerConfigResponse', (_message.Message,), dict(
  DESCRIPTOR = _ANALYZERCONFIGRESPONSE,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.AnalyzerConfigResponse)
  ))
_sym_db.RegisterMessage(AnalyzerConfigResponse)

InfoNodesMessage = _reflection.GeneratedProtocolMessageType('InfoNodesMessage', (_message.Message,), dict(
  DESCRIPTOR = _INFONODESMESSAGE,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.InfoNodesMessage)
  ))
_sym_db.RegisterMessage(InfoNodesMessage)

DiagnosticNodeMessage = _reflection.GeneratedProtocolMessageType('DiagnosticNodeMessage', (_message.Message,), dict(
  DESCRIPTOR = _DIAGNOSTICNODEMESSAGE,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.DiagnosticNodeMessage)
  ))
_sym_db.RegisterMessage(DiagnosticNodeMessage)

SendResponse = _reflection.GeneratedProtocolMessageType('SendResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDRESPONSE,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.SendResponse)
  ))
_sym_db.RegisterMessage(SendResponse)

DummyRequest = _reflection.GeneratedProtocolMessageType('DummyRequest', (_message.Message,), dict(
  DESCRIPTOR = _DUMMYREQUEST,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.DummyRequest)
  ))
_sym_db.RegisterMessage(DummyRequest)


DESCRIPTOR._options = None

_ANALYSISSERVICE = _descriptor.ServiceDescriptor(
  name='AnalysisService',
  full_name='service.AnalysisService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=399,
  serialized_end=724,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAnalyzerConfig',
    full_name='service.AnalysisService.GetAnalyzerConfig',
    index=0,
    containing_service=None,
    input_type=_ANALYZERCONFIGREQUEST,
    output_type=_ANALYZERCONFIGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendInfoNodes',
    full_name='service.AnalysisService.SendInfoNodes',
    index=1,
    containing_service=None,
    input_type=_INFONODESMESSAGE,
    output_type=_SENDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendDiagnosticNode',
    full_name='service.AnalysisService.SendDiagnosticNode',
    index=2,
    containing_service=None,
    input_type=_DIAGNOSTICNODEMESSAGE,
    output_type=_SENDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSourceFileNodes',
    full_name='service.AnalysisService.GetSourceFileNodes',
    index=3,
    containing_service=None,
    input_type=_DUMMYREQUEST,
    output_type=datamodel__pb2._FILENODE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALYSISSERVICE)

DESCRIPTOR.services_by_name['AnalysisService'] = _ANALYSISSERVICE

# @@protoc_insertion_point(module_scope)
