# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyzerservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import datamodel_pb2 as datamodel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='analyzerservice.proto',
  package='service',
  syntax='proto3',
  serialized_options=_b('\n\026org.qmstr.grpc.service'),
  serialized_pb=_b('\n\x15\x61nalyzerservice.proto\x12\x07service\x1a\x0f\x64\x61tamodel.proto\"+\n\x15\x41nalyzerConfigRequest\x12\x12\n\nanalyzerID\x18\x01 \x01(\x05\"\xd6\x01\n\x16\x41nalyzerConfigResponse\x12\x41\n\tconfigMap\x18\x02 \x03(\x0b\x32..service.AnalyzerConfigResponse.ConfigMapEntry\x12*\n\x07pathSub\x18\x03 \x03(\x0b\x32\x19.service.PathSubstitution\x12\r\n\x05token\x18\x04 \x01(\x03\x12\x0c\n\x04name\x18\x06 \x01(\t\x1a\x30\n\x0e\x43onfigMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"R\n\x0fInfoNodeMessage\x12\r\n\x05token\x18\x01 \x01(\x03\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12#\n\x08infonode\x18\x03 \x01(\x0b\x32\x11.service.InfoNode\"E\n\x0f\x46ileNodeMessage\x12\r\n\x05token\x18\x01 \x01(\x03\x12#\n\x08\x66ilenode\x18\x02 \x01(\x0b\x32\x11.service.FileNode\"N\n\x12PackageNodeMessage\x12\r\n\x05token\x18\x01 \x01(\x03\x12)\n\x0bpackagenode\x18\x02 \x01(\x0b\x32\x14.service.PackageNode\"d\n\x15\x44iagnosticNodeMessage\x12\r\n\x05token\x18\x01 \x01(\x03\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12/\n\x0e\x64iagnosticnode\x18\x03 \x01(\x0b\x32\x17.service.DiagnosticNode\"\x1f\n\x0cSendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x90\x03\n\x0f\x41nalysisService\x12V\n\x11GetAnalyzerConfig\x12\x1e.service.AnalyzerConfigRequest\x1a\x1f.service.AnalyzerConfigResponse\"\x00\x12\x44\n\rSendInfoNodes\x12\x18.service.InfoNodeMessage\x1a\x15.service.SendResponse\"\x00(\x01\x12\x43\n\x0cSendFileNode\x12\x18.service.FileNodeMessage\x1a\x15.service.SendResponse\"\x00(\x01\x12I\n\x0fSendPackageNode\x12\x1b.service.PackageNodeMessage\x1a\x15.service.SendResponse\"\x00(\x01\x12O\n\x12SendDiagnosticNode\x12\x1e.service.DiagnosticNodeMessage\x1a\x15.service.SendResponse\"\x00(\x01\x42\x18\n\x16org.qmstr.grpc.serviceX\x00\x62\x06proto3')
  ,
  dependencies=[datamodel__pb2.DESCRIPTOR,])




_ANALYZERCONFIGREQUEST = _descriptor.Descriptor(
  name='AnalyzerConfigRequest',
  full_name='service.AnalyzerConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='analyzerID', full_name='service.AnalyzerConfigRequest.analyzerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=94,
)


_ANALYZERCONFIGRESPONSE_CONFIGMAPENTRY = _descriptor.Descriptor(
  name='ConfigMapEntry',
  full_name='service.AnalyzerConfigResponse.ConfigMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='service.AnalyzerConfigResponse.ConfigMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='service.AnalyzerConfigResponse.ConfigMapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=311,
)

_ANALYZERCONFIGRESPONSE = _descriptor.Descriptor(
  name='AnalyzerConfigResponse',
  full_name='service.AnalyzerConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configMap', full_name='service.AnalyzerConfigResponse.configMap', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pathSub', full_name='service.AnalyzerConfigResponse.pathSub', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='service.AnalyzerConfigResponse.token', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='service.AnalyzerConfigResponse.name', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ANALYZERCONFIGRESPONSE_CONFIGMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=311,
)


_INFONODEMESSAGE = _descriptor.Descriptor(
  name='InfoNodeMessage',
  full_name='service.InfoNodeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='service.InfoNodeMessage.token', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='service.InfoNodeMessage.uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infonode', full_name='service.InfoNodeMessage.infonode', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=395,
)


_FILENODEMESSAGE = _descriptor.Descriptor(
  name='FileNodeMessage',
  full_name='service.FileNodeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='service.FileNodeMessage.token', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filenode', full_name='service.FileNodeMessage.filenode', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=466,
)


_PACKAGENODEMESSAGE = _descriptor.Descriptor(
  name='PackageNodeMessage',
  full_name='service.PackageNodeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='service.PackageNodeMessage.token', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packagenode', full_name='service.PackageNodeMessage.packagenode', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=546,
)


_DIAGNOSTICNODEMESSAGE = _descriptor.Descriptor(
  name='DiagnosticNodeMessage',
  full_name='service.DiagnosticNodeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='service.DiagnosticNodeMessage.token', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='service.DiagnosticNodeMessage.uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagnosticnode', full_name='service.DiagnosticNodeMessage.diagnosticnode', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=648,
)


_SENDRESPONSE = _descriptor.Descriptor(
  name='SendResponse',
  full_name='service.SendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='service.SendResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=650,
  serialized_end=681,
)

_ANALYZERCONFIGRESPONSE_CONFIGMAPENTRY.containing_type = _ANALYZERCONFIGRESPONSE
_ANALYZERCONFIGRESPONSE.fields_by_name['configMap'].message_type = _ANALYZERCONFIGRESPONSE_CONFIGMAPENTRY
_ANALYZERCONFIGRESPONSE.fields_by_name['pathSub'].message_type = datamodel__pb2._PATHSUBSTITUTION
_INFONODEMESSAGE.fields_by_name['infonode'].message_type = datamodel__pb2._INFONODE
_FILENODEMESSAGE.fields_by_name['filenode'].message_type = datamodel__pb2._FILENODE
_PACKAGENODEMESSAGE.fields_by_name['packagenode'].message_type = datamodel__pb2._PACKAGENODE
_DIAGNOSTICNODEMESSAGE.fields_by_name['diagnosticnode'].message_type = datamodel__pb2._DIAGNOSTICNODE
DESCRIPTOR.message_types_by_name['AnalyzerConfigRequest'] = _ANALYZERCONFIGREQUEST
DESCRIPTOR.message_types_by_name['AnalyzerConfigResponse'] = _ANALYZERCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['InfoNodeMessage'] = _INFONODEMESSAGE
DESCRIPTOR.message_types_by_name['FileNodeMessage'] = _FILENODEMESSAGE
DESCRIPTOR.message_types_by_name['PackageNodeMessage'] = _PACKAGENODEMESSAGE
DESCRIPTOR.message_types_by_name['DiagnosticNodeMessage'] = _DIAGNOSTICNODEMESSAGE
DESCRIPTOR.message_types_by_name['SendResponse'] = _SENDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalyzerConfigRequest = _reflection.GeneratedProtocolMessageType('AnalyzerConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _ANALYZERCONFIGREQUEST,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.AnalyzerConfigRequest)
  ))
_sym_db.RegisterMessage(AnalyzerConfigRequest)

AnalyzerConfigResponse = _reflection.GeneratedProtocolMessageType('AnalyzerConfigResponse', (_message.Message,), dict(

  ConfigMapEntry = _reflection.GeneratedProtocolMessageType('ConfigMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _ANALYZERCONFIGRESPONSE_CONFIGMAPENTRY,
    __module__ = 'analyzerservice_pb2'
    # @@protoc_insertion_point(class_scope:service.AnalyzerConfigResponse.ConfigMapEntry)
    ))
  ,
  DESCRIPTOR = _ANALYZERCONFIGRESPONSE,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.AnalyzerConfigResponse)
  ))
_sym_db.RegisterMessage(AnalyzerConfigResponse)
_sym_db.RegisterMessage(AnalyzerConfigResponse.ConfigMapEntry)

InfoNodeMessage = _reflection.GeneratedProtocolMessageType('InfoNodeMessage', (_message.Message,), dict(
  DESCRIPTOR = _INFONODEMESSAGE,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.InfoNodeMessage)
  ))
_sym_db.RegisterMessage(InfoNodeMessage)

FileNodeMessage = _reflection.GeneratedProtocolMessageType('FileNodeMessage', (_message.Message,), dict(
  DESCRIPTOR = _FILENODEMESSAGE,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.FileNodeMessage)
  ))
_sym_db.RegisterMessage(FileNodeMessage)

PackageNodeMessage = _reflection.GeneratedProtocolMessageType('PackageNodeMessage', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGENODEMESSAGE,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.PackageNodeMessage)
  ))
_sym_db.RegisterMessage(PackageNodeMessage)

DiagnosticNodeMessage = _reflection.GeneratedProtocolMessageType('DiagnosticNodeMessage', (_message.Message,), dict(
  DESCRIPTOR = _DIAGNOSTICNODEMESSAGE,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.DiagnosticNodeMessage)
  ))
_sym_db.RegisterMessage(DiagnosticNodeMessage)

SendResponse = _reflection.GeneratedProtocolMessageType('SendResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDRESPONSE,
  __module__ = 'analyzerservice_pb2'
  # @@protoc_insertion_point(class_scope:service.SendResponse)
  ))
_sym_db.RegisterMessage(SendResponse)


DESCRIPTOR._options = None
_ANALYZERCONFIGRESPONSE_CONFIGMAPENTRY._options = None

_ANALYSISSERVICE = _descriptor.ServiceDescriptor(
  name='AnalysisService',
  full_name='service.AnalysisService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=684,
  serialized_end=1084,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAnalyzerConfig',
    full_name='service.AnalysisService.GetAnalyzerConfig',
    index=0,
    containing_service=None,
    input_type=_ANALYZERCONFIGREQUEST,
    output_type=_ANALYZERCONFIGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendInfoNodes',
    full_name='service.AnalysisService.SendInfoNodes',
    index=1,
    containing_service=None,
    input_type=_INFONODEMESSAGE,
    output_type=_SENDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendFileNode',
    full_name='service.AnalysisService.SendFileNode',
    index=2,
    containing_service=None,
    input_type=_FILENODEMESSAGE,
    output_type=_SENDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendPackageNode',
    full_name='service.AnalysisService.SendPackageNode',
    index=3,
    containing_service=None,
    input_type=_PACKAGENODEMESSAGE,
    output_type=_SENDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendDiagnosticNode',
    full_name='service.AnalysisService.SendDiagnosticNode',
    index=4,
    containing_service=None,
    input_type=_DIAGNOSTICNODEMESSAGE,
    output_type=_SENDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALYSISSERVICE)

DESCRIPTOR.services_by_name['AnalysisService'] = _ANALYSISSERVICE

# @@protoc_insertion_point(module_scope)
