# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import datamodel_pb2 as datamodel__pb2
from . import reportservice_pb2 as reportservice__pb2


class ReportServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetReporterConfig = channel.unary_unary(
        '/service.ReportService/GetReporterConfig',
        request_serializer=reportservice__pb2.ReporterConfigRequest.SerializeToString,
        response_deserializer=reportservice__pb2.ReporterConfigResponse.FromString,
        )
    self.GetInfoData = channel.unary_unary(
        '/service.ReportService/GetInfoData',
        request_serializer=reportservice__pb2.InfoDataRequest.SerializeToString,
        response_deserializer=reportservice__pb2.InfoDataResponse.FromString,
        )
    self.GetProjectNode = channel.unary_unary(
        '/service.ReportService/GetProjectNode',
        request_serializer=datamodel__pb2.ProjectNode.SerializeToString,
        response_deserializer=datamodel__pb2.ProjectNode.FromString,
        )


class ReportServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetReporterConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInfoData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProjectNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReportServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetReporterConfig': grpc.unary_unary_rpc_method_handler(
          servicer.GetReporterConfig,
          request_deserializer=reportservice__pb2.ReporterConfigRequest.FromString,
          response_serializer=reportservice__pb2.ReporterConfigResponse.SerializeToString,
      ),
      'GetInfoData': grpc.unary_unary_rpc_method_handler(
          servicer.GetInfoData,
          request_deserializer=reportservice__pb2.InfoDataRequest.FromString,
          response_serializer=reportservice__pb2.InfoDataResponse.SerializeToString,
      ),
      'GetProjectNode': grpc.unary_unary_rpc_method_handler(
          servicer.GetProjectNode,
          request_deserializer=datamodel__pb2.ProjectNode.FromString,
          response_serializer=datamodel__pb2.ProjectNode.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'service.ReportService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
