# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reportservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import bom_pb2 as bom__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='reportservice.proto',
  package='service',
  syntax='proto3',
  serialized_options=_b('\n\026org.qmstr.grpc.service'),
  serialized_pb=_b('\n\x13reportservice.proto\x12\x07service\x1a\tbom.proto\"+\n\x15ReporterConfigRequest\x12\x12\n\nreporterID\x18\x01 \x01(\x05\"\x9b\x01\n\x16ReporterConfigResponse\x12\x41\n\tconfigMap\x18\x01 \x03(\x0b\x32..service.ReporterConfigResponse.ConfigMapEntry\x12\x0c\n\x04name\x18\x02 \x01(\t\x1a\x30\n\x0e\x43onfigMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"E\n\x0fInfoDataRequest\x12\x0e\n\x06rootID\x18\x01 \x01(\t\x12\x10\n\x08infotype\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61tatype\x18\x03 \x01(\t\" \n\x10InfoDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\".\n\nBOMRequest\x12\x10\n\x08warnings\x18\x01 \x01(\x08\x12\x0e\n\x06\x65rrors\x18\x02 \x01(\x08\x32\xdc\x01\n\rReportService\x12V\n\x11GetReporterConfig\x12\x1e.service.ReporterConfigRequest\x1a\x1f.service.ReporterConfigResponse\"\x00\x12\x44\n\x0bGetInfoData\x12\x18.service.InfoDataRequest\x1a\x19.service.InfoDataResponse\"\x00\x12-\n\x06GetBOM\x12\x13.service.BOMRequest\x1a\x0c.service.BOM\"\x00\x42\x18\n\x16org.qmstr.grpc.serviceX\x00\x62\x06proto3')
  ,
  dependencies=[bom__pb2.DESCRIPTOR,])




_REPORTERCONFIGREQUEST = _descriptor.Descriptor(
  name='ReporterConfigRequest',
  full_name='service.ReporterConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reporterID', full_name='service.ReporterConfigRequest.reporterID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=86,
)


_REPORTERCONFIGRESPONSE_CONFIGMAPENTRY = _descriptor.Descriptor(
  name='ConfigMapEntry',
  full_name='service.ReporterConfigResponse.ConfigMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='service.ReporterConfigResponse.ConfigMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='service.ReporterConfigResponse.ConfigMapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=244,
)

_REPORTERCONFIGRESPONSE = _descriptor.Descriptor(
  name='ReporterConfigResponse',
  full_name='service.ReporterConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configMap', full_name='service.ReporterConfigResponse.configMap', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='service.ReporterConfigResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REPORTERCONFIGRESPONSE_CONFIGMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=244,
)


_INFODATAREQUEST = _descriptor.Descriptor(
  name='InfoDataRequest',
  full_name='service.InfoDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rootID', full_name='service.InfoDataRequest.rootID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infotype', full_name='service.InfoDataRequest.infotype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datatype', full_name='service.InfoDataRequest.datatype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=315,
)


_INFODATARESPONSE = _descriptor.Descriptor(
  name='InfoDataResponse',
  full_name='service.InfoDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='service.InfoDataResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=349,
)


_BOMREQUEST = _descriptor.Descriptor(
  name='BOMRequest',
  full_name='service.BOMRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='warnings', full_name='service.BOMRequest.warnings', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='service.BOMRequest.errors', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=397,
)

_REPORTERCONFIGRESPONSE_CONFIGMAPENTRY.containing_type = _REPORTERCONFIGRESPONSE
_REPORTERCONFIGRESPONSE.fields_by_name['configMap'].message_type = _REPORTERCONFIGRESPONSE_CONFIGMAPENTRY
DESCRIPTOR.message_types_by_name['ReporterConfigRequest'] = _REPORTERCONFIGREQUEST
DESCRIPTOR.message_types_by_name['ReporterConfigResponse'] = _REPORTERCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['InfoDataRequest'] = _INFODATAREQUEST
DESCRIPTOR.message_types_by_name['InfoDataResponse'] = _INFODATARESPONSE
DESCRIPTOR.message_types_by_name['BOMRequest'] = _BOMREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReporterConfigRequest = _reflection.GeneratedProtocolMessageType('ReporterConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _REPORTERCONFIGREQUEST,
  __module__ = 'reportservice_pb2'
  # @@protoc_insertion_point(class_scope:service.ReporterConfigRequest)
  ))
_sym_db.RegisterMessage(ReporterConfigRequest)

ReporterConfigResponse = _reflection.GeneratedProtocolMessageType('ReporterConfigResponse', (_message.Message,), dict(

  ConfigMapEntry = _reflection.GeneratedProtocolMessageType('ConfigMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _REPORTERCONFIGRESPONSE_CONFIGMAPENTRY,
    __module__ = 'reportservice_pb2'
    # @@protoc_insertion_point(class_scope:service.ReporterConfigResponse.ConfigMapEntry)
    ))
  ,
  DESCRIPTOR = _REPORTERCONFIGRESPONSE,
  __module__ = 'reportservice_pb2'
  # @@protoc_insertion_point(class_scope:service.ReporterConfigResponse)
  ))
_sym_db.RegisterMessage(ReporterConfigResponse)
_sym_db.RegisterMessage(ReporterConfigResponse.ConfigMapEntry)

InfoDataRequest = _reflection.GeneratedProtocolMessageType('InfoDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _INFODATAREQUEST,
  __module__ = 'reportservice_pb2'
  # @@protoc_insertion_point(class_scope:service.InfoDataRequest)
  ))
_sym_db.RegisterMessage(InfoDataRequest)

InfoDataResponse = _reflection.GeneratedProtocolMessageType('InfoDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _INFODATARESPONSE,
  __module__ = 'reportservice_pb2'
  # @@protoc_insertion_point(class_scope:service.InfoDataResponse)
  ))
_sym_db.RegisterMessage(InfoDataResponse)

BOMRequest = _reflection.GeneratedProtocolMessageType('BOMRequest', (_message.Message,), dict(
  DESCRIPTOR = _BOMREQUEST,
  __module__ = 'reportservice_pb2'
  # @@protoc_insertion_point(class_scope:service.BOMRequest)
  ))
_sym_db.RegisterMessage(BOMRequest)


DESCRIPTOR._options = None
_REPORTERCONFIGRESPONSE_CONFIGMAPENTRY._options = None

_REPORTSERVICE = _descriptor.ServiceDescriptor(
  name='ReportService',
  full_name='service.ReportService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=400,
  serialized_end=620,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetReporterConfig',
    full_name='service.ReportService.GetReporterConfig',
    index=0,
    containing_service=None,
    input_type=_REPORTERCONFIGREQUEST,
    output_type=_REPORTERCONFIGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetInfoData',
    full_name='service.ReportService.GetInfoData',
    index=1,
    containing_service=None,
    input_type=_INFODATAREQUEST,
    output_type=_INFODATARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBOM',
    full_name='service.ReportService.GetBOM',
    index=2,
    containing_service=None,
    input_type=_BOMREQUEST,
    output_type=bom__pb2._BOM,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPORTSERVICE)

DESCRIPTOR.services_by_name['ReportService'] = _REPORTSERVICE

# @@protoc_insertion_point(module_scope)
