apiVersion: v1
kind: ConfigMap
metadata:
  name: qmstr-config
  namespace: default
data:
  qmstrConfig: |-
    project:
      name: "CI"
      metadata:
        message: "Hello World!"
      analysis:
        - analyzer: test-analyzer
          name: "Simple CI Test Analyzer"
          config:
            workdir: "/home/qmstr/test/"
            tests: "TestPackageNode;TestCI"
