pipeline {
    agent any

    stages {
        stage('test') {
            steps {
                sh 'make gotest'
            }
        }
        stage('checkpep8') {
            steps {
                sh 'make checkpep8'
            }
        }
        stage('golint') {
            steps {
                sh 'make golint'
            }
        }
        stage('govet') {
            steps {
                sh 'make govet'
            }
        }
    }
}
