apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/job.yaml
configMapGenerator:
  # Overridable repo URL
  - name: repo-url
    env: repo-url.env
  # Master configuration file
  - name: qmstr-config
    files:
      - base/qmstr.yaml

commonLabels:
  app: qmstr

# In case of manual deployment, insert the desired image tags here.
#images:
#  - name: endocodeci/qmstr-master
#    newTag: sha-...
#  - name: endocodeci/qmstr-client-mvn
#    newTag: sha-...
#  - name: endocodeci/pom-patch
#    newTag: sha-...
