apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml
configMapGenerator:
  # Master configuration file
  - name: qmstr-config
    files:
      - qmstr.yaml
commonLabels:
  app: qmstr
