apiVersion: batch/v1
kind: Job
metadata:
  name: qmstr
spec:
  template:
    spec:
      initContainers:
        - name: repo-cloner
          env:
            - name: GIT_SYNC_REPO
              value: https://github.com/biojava/biojava
