pipeline {

    agent { label 'linux' }

    triggers {
        pollSCM('H/10 * * * *')
    }

    environment {
    	VAGRANT_VAGRANTFILE = 'docker/Vagrantfile'
    }

    stages {
        stage('DocTest') {
            steps {
	    	sh 'git clean -ffxd'
                sh 'vagrant up'
                sh 'vagrant ssh -c /vagrant/docker/vagrant-test-documentation-driver.sh'
            }
        }
    }

    post {
        always {
            sh 'vagrant destroy -f'
        }
    }
}