baseURL = "https://qmstr.org/documentation"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Quartermaster - Documentation"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
enableGitInfo = "true"
canonifyURLs = true

[Params]

    # Souce Code repository section
    description = "QMSTR creates an integrated Open Source toolchain that implements industry best practises of license compliance management."
    # github_repository = "https://github.com/QMSTR/qmstr"
    # version = "0.3"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    # Mirko: disabled because of integration into shelldoc tests:
    # github_doc_repository = "https://github.com/QMSTR/qmstr"

    # Analytic section
    google_analytics_id = "UA-40601155-2"
    # tag_manager_container_id = "" # Your Google Tag Manager container id
    # google_site_verification = "" # Your Google Site Verification

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = ["archives", "blog", "entry", "post", "posts"]

    # additional CSS code for the site:
    custom_css = ["css/qmstr.css"]

# Global menu section
[[menu.main]]
    name = "Documentation"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Main Website"
    url = "https://qmstr.org"
    weight = 2

[[menu.main]]
    name = "Repositories"
    url = "https://github.com/QMSTR"
    weight = 3

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/fosscompliance"
    weight = 4

