JAVAQMSTR := java-qmstr
QMSTR_JAVALIB_SRC := $(shell find lib/$(JAVAQMSTR)/src -name "*.java")

.PHONY := $(JAVAQMSTR)
$(JAVAQMSTR): lib/$(JAVAQMSTR)/build/libs/service-$(QMSTR_VERSION).jar

lib/$(JAVAQMSTR)/build/libs/service-$(QMSTR_VERSION).jar: $(QMSTR_JAVALIB_SRC)
	cd lib/java-qmstr && ./gradlew install