GIT_ANALYZER := git-analyzer

.PHONY: $(GIT_ANALYZER)
$(GIT_ANALYZER): $(OUTDIR)analyzers/$(GIT_ANALYZER)

$(OUTDIR)analyzers/$(GIT_ANALYZER): $(GO_SRCS)
	go test ./modules/$(subst $(OUTDIR),,$@)
	go build -o $@ ./modules/$(subst $(OUTDIR),,$@)