SPDX_REPORTER := spdx-reporter

.PHONY: $(SPDX_REPORTER)
$(SPDX_REPORTER): $(OUTDIR)reporters/$(SPDX_REPORTER)

$(OUTDIR)reporters/$(SPDX_REPORTER): $(GO_SRCS)
	go test github.com/QMSTR/qmstr/modules/$(subst $(OUTDIR),,$@)
	go build -o $@ github.com/QMSTR/qmstr/modules/$(subst $(OUTDIR),,$@)