QMSTR_GRADLE_PLUGIN := qmstr-gradle-plugin
QMSTR_GRADLE_SRC := $(shell find modules/builders/$(QMSTR_GRADLE_PLUGIN)/src -name "*.java")

.PHONY := $(QMSTR_GRADLE_PLUGIN)
$(QMSTR_GRADLE_PLUGIN): $(OUTDIR)builders/$(QMSTR_GRADLE_PLUGIN)/build/libs/gradle-plugin-$(QMSTR_VERSION).jar

$(OUTDIR)builders/$(QMSTR_GRADLE_PLUGIN)/build/libs/gradle-plugin-$(QMSTR_VERSION).jar: $(QMSTR_GRADLE_SRC)
	cd modules/builders/qmstr-gradle-plugin && ./gradlew install