// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buildservice.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BuildResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildservice_811cd69d1da34bdf, []int{0}
}
func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (dst *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(dst, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PushFileMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushFileMessage) Reset()         { *m = PushFileMessage{} }
func (m *PushFileMessage) String() string { return proto.CompactTextString(m) }
func (*PushFileMessage) ProtoMessage()    {}
func (*PushFileMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildservice_811cd69d1da34bdf, []int{1}
}
func (m *PushFileMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushFileMessage.Unmarshal(m, b)
}
func (m *PushFileMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushFileMessage.Marshal(b, m, deterministic)
}
func (dst *PushFileMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushFileMessage.Merge(dst, src)
}
func (m *PushFileMessage) XXX_Size() int {
	return xxx_messageInfo_PushFileMessage.Size(m)
}
func (m *PushFileMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PushFileMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PushFileMessage proto.InternalMessageInfo

func (m *PushFileMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PushFileMessage) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *PushFileMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PushFileResponse struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushFileResponse) Reset()         { *m = PushFileResponse{} }
func (m *PushFileResponse) String() string { return proto.CompactTextString(m) }
func (*PushFileResponse) ProtoMessage()    {}
func (*PushFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_buildservice_811cd69d1da34bdf, []int{2}
}
func (m *PushFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushFileResponse.Unmarshal(m, b)
}
func (m *PushFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushFileResponse.Marshal(b, m, deterministic)
}
func (dst *PushFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushFileResponse.Merge(dst, src)
}
func (m *PushFileResponse) XXX_Size() int {
	return xxx_messageInfo_PushFileResponse.Size(m)
}
func (m *PushFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushFileResponse proto.InternalMessageInfo

func (m *PushFileResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildResponse)(nil), "service.BuildResponse")
	proto.RegisterType((*PushFileMessage)(nil), "service.PushFileMessage")
	proto.RegisterType((*PushFileResponse)(nil), "service.PushFileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuildServiceClient interface {
	Build(ctx context.Context, opts ...grpc.CallOption) (BuildService_BuildClient, error)
	SendBuildError(ctx context.Context, in *InfoNode, opts ...grpc.CallOption) (*BuildResponse, error)
	PushFile(ctx context.Context, in *PushFileMessage, opts ...grpc.CallOption) (*PushFileResponse, error)
	Package(ctx context.Context, opts ...grpc.CallOption) (BuildService_PackageClient, error)
}

type buildServiceClient struct {
	cc *grpc.ClientConn
}

func NewBuildServiceClient(cc *grpc.ClientConn) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) Build(ctx context.Context, opts ...grpc.CallOption) (BuildService_BuildClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BuildService_serviceDesc.Streams[0], "/service.BuildService/Build", opts...)
	if err != nil {
		return nil, err
	}
	x := &buildServiceBuildClient{stream}
	return x, nil
}

type BuildService_BuildClient interface {
	Send(*FileNode) error
	CloseAndRecv() (*BuildResponse, error)
	grpc.ClientStream
}

type buildServiceBuildClient struct {
	grpc.ClientStream
}

func (x *buildServiceBuildClient) Send(m *FileNode) error {
	return x.ClientStream.SendMsg(m)
}

func (x *buildServiceBuildClient) CloseAndRecv() (*BuildResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BuildResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *buildServiceClient) SendBuildError(ctx context.Context, in *InfoNode, opts ...grpc.CallOption) (*BuildResponse, error) {
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, "/service.BuildService/SendBuildError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) PushFile(ctx context.Context, in *PushFileMessage, opts ...grpc.CallOption) (*PushFileResponse, error) {
	out := new(PushFileResponse)
	err := c.cc.Invoke(ctx, "/service.BuildService/PushFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) Package(ctx context.Context, opts ...grpc.CallOption) (BuildService_PackageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BuildService_serviceDesc.Streams[1], "/service.BuildService/Package", opts...)
	if err != nil {
		return nil, err
	}
	x := &buildServicePackageClient{stream}
	return x, nil
}

type BuildService_PackageClient interface {
	Send(*FileNode) error
	CloseAndRecv() (*BuildResponse, error)
	grpc.ClientStream
}

type buildServicePackageClient struct {
	grpc.ClientStream
}

func (x *buildServicePackageClient) Send(m *FileNode) error {
	return x.ClientStream.SendMsg(m)
}

func (x *buildServicePackageClient) CloseAndRecv() (*BuildResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BuildResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BuildServiceServer is the server API for BuildService service.
type BuildServiceServer interface {
	Build(BuildService_BuildServer) error
	SendBuildError(context.Context, *InfoNode) (*BuildResponse, error)
	PushFile(context.Context, *PushFileMessage) (*PushFileResponse, error)
	Package(BuildService_PackageServer) error
}

func RegisterBuildServiceServer(s *grpc.Server, srv BuildServiceServer) {
	s.RegisterService(&_BuildService_serviceDesc, srv)
}

func _BuildService_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BuildServiceServer).Build(&buildServiceBuildServer{stream})
}

type BuildService_BuildServer interface {
	SendAndClose(*BuildResponse) error
	Recv() (*FileNode, error)
	grpc.ServerStream
}

type buildServiceBuildServer struct {
	grpc.ServerStream
}

func (x *buildServiceBuildServer) SendAndClose(m *BuildResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *buildServiceBuildServer) Recv() (*FileNode, error) {
	m := new(FileNode)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BuildService_SendBuildError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).SendBuildError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.BuildService/SendBuildError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).SendBuildError(ctx, req.(*InfoNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_PushFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushFileMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).PushFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.BuildService/PushFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).PushFile(ctx, req.(*PushFileMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_Package_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BuildServiceServer).Package(&buildServicePackageServer{stream})
}

type BuildService_PackageServer interface {
	SendAndClose(*BuildResponse) error
	Recv() (*FileNode, error)
	grpc.ServerStream
}

type buildServicePackageServer struct {
	grpc.ServerStream
}

func (x *buildServicePackageServer) SendAndClose(m *BuildResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *buildServicePackageServer) Recv() (*FileNode, error) {
	m := new(FileNode)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BuildService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBuildError",
			Handler:    _BuildService_SendBuildError_Handler,
		},
		{
			MethodName: "PushFile",
			Handler:    _BuildService_PushFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Build",
			Handler:       _BuildService_Build_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Package",
			Handler:       _BuildService_Package_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "buildservice.proto",
}

func init() { proto.RegisterFile("buildservice.proto", fileDescriptor_buildservice_811cd69d1da34bdf) }

var fileDescriptor_buildservice_811cd69d1da34bdf = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x5a, 0x6d, 0x1d, 0xaa, 0xd5, 0x39, 0x94, 0xb5, 0xa7, 0x92, 0x83, 0xd4, 0x4b,
	0x0e, 0x0a, 0xe2, 0xc5, 0x83, 0x05, 0x05, 0x0f, 0x95, 0x92, 0x5e, 0xbc, 0x6e, 0x93, 0x31, 0x09,
	0x26, 0xd9, 0xb8, 0x93, 0xf8, 0x03, 0xfc, 0xe5, 0xb2, 0x1b, 0x37, 0x54, 0x05, 0xc1, 0xdb, 0x9b,
	0x37, 0x8f, 0x6f, 0x67, 0x66, 0x01, 0xb7, 0x4d, 0x96, 0xc7, 0x4c, 0xfa, 0x3d, 0x8b, 0x28, 0xa8,
	0xb4, 0xaa, 0x15, 0x0e, 0xbf, 0xca, 0xd9, 0x24, 0x96, 0xb5, 0x2c, 0x54, 0x4c, 0x79, 0xdb, 0xf1,
	0x2f, 0xe0, 0x68, 0x69, 0xf2, 0x21, 0x71, 0xa5, 0x4a, 0x26, 0x14, 0x30, 0xe4, 0x26, 0x8a, 0x88,
	0x59, 0x78, 0x73, 0x6f, 0x31, 0x0a, 0x5d, 0xe9, 0xaf, 0x60, 0xb2, 0x6e, 0x38, 0x7d, 0xc8, 0x72,
	0x5a, 0x11, 0xb3, 0x4c, 0x08, 0x11, 0x06, 0xa5, 0x2c, 0xc8, 0x26, 0x0f, 0x43, 0xab, 0x8d, 0x97,
	0x4a, 0x4e, 0x45, 0xbf, 0xf5, 0x8c, 0x36, 0x9e, 0x79, 0x58, 0xec, 0xcd, 0xbd, 0xc5, 0x38, 0xb4,
	0xda, 0x3f, 0x87, 0x13, 0x87, 0xeb, 0x1e, 0x47, 0x18, 0x54, 0xb2, 0x4e, 0x1d, 0xcf, 0xe8, 0xcb,
	0x8f, 0x3e, 0x8c, 0xed, 0x88, 0x9b, 0x76, 0x07, 0xbc, 0x86, 0x7d, 0x5b, 0xe3, 0x69, 0xe0, 0xb6,
	0x34, 0x90, 0x27, 0x15, 0xd3, 0x6c, 0xda, 0x59, 0xdf, 0xb6, 0xf2, 0x7b, 0x0b, 0x0f, 0x6f, 0xe1,
	0x78, 0x43, 0x65, 0x6c, 0x1b, 0xf7, 0x5a, 0x2b, 0xbd, 0x03, 0x78, 0x2c, 0x5f, 0xd4, 0xdf, 0x00,
	0xbc, 0x83, 0x91, 0x9b, 0x17, 0x45, 0x97, 0xfa, 0x71, 0x91, 0xd9, 0xd9, 0xaf, 0xce, 0x0e, 0xe2,
	0x06, 0x86, 0x6b, 0x19, 0xbd, 0x9a, 0xcb, 0xfd, 0x6f, 0xf6, 0xa5, 0x80, 0xa9, 0xd2, 0x49, 0xf0,
	0x56, 0x70, 0xad, 0x83, 0x44, 0x57, 0x91, 0xcb, 0x3e, 0xf7, 0xb6, 0x07, 0xf6, 0x27, 0xaf, 0x3e,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x88, 0xfc, 0x8d, 0xea, 0xf9, 0x01, 0x00, 0x00,
}
