stage('document_test') {
    node('linux') {
        sh '''#!/bin/bash -e
            export VAGRANT_VAGRANTFILE=ci/Vagrantfile
            vagrant up
            vagrant ssh -c /vagrant/ci/vagrant-test-documentation-driver.sh
            RESULT=$?
            vagrant destroy -f
        '''
    }
}