VAGRANT_CMD := VAGRANT_VAGRANTFILE='ci/Vagrantfile' vagrant

.PHONY: doctest_start doctest_exit doctest
doctest: doctest_start doctest_exit

doctest_start:
	$(VAGRANT_CMD) up
	$(VAGRANT_CMD) ssh -c /vagrant/ci/vagrant-test-documentation-driver.sh

doctest_exit:
	$(VAGRANT_CMD) destroy -f
