Vagrant.require_version ">= 1.9"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  if (/darwin/ =~ RUBY_PLATFORM) != nil
    config.vm.network "private_network", type: "dhcp"
    config.vm.synced_folder ".", "/vagrant", type: "nfs"
  end
  config.vm.provision :shell, path: "ci/vagrant-bootstrap.sh"
end
