Vagrant.require_version ">= 2.0"
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1810"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision :shell, path: "ci/vagrant-bootstrap.sh"
end
