CONSOLE_REPORTER := console-reporter

.PHONY: $(CONSOLE_REPORTER)
$(CONSOLE_REPORTER): $(OUTDIR)reporters/$(CONSOLE_REPORTER)

$(OUTDIR)reporters/$(CONSOLE_REPORTER): $(GO_SRCS)
	go test ./modules/$(subst $(OUTDIR),,$@)
	go build -o $@ ./modules/$(subst $(OUTDIR),,$@)