CONSOLE_REPORTER := console-reporter

.PHONY: $(CONSOLE_REPORTER)
$(CONSOLE_REPORTER): $(OUTDIR)reporters/$(CONSOLE_REPORTER)

$(OUTDIR)reporters/$(CONSOLE_REPORTER): $(GO_SRCS)
	go test github.com/QMSTR/qmstr/modules/$(subst $(OUTDIR),,$@)
	go build -o $@ github.com/QMSTR/qmstr/modules/$(subst $(OUTDIR),,$@)