QMSTRCTL := qmstrctl

.PHONY: $(QMSTRCTL)
$(QMSTRCTL): $(OUTDIR)$(QMSTRCTL)

$(OUTDIR)$(QMSTRCTL): $(GO_DEPS)
	go test ./clients/$(subst $(OUTDIR),,$@)
	go build -o $@ ./clients/$(subst $(OUTDIR),,$@)
