apiVersion: batch/v1
kind: Job
metadata:
  name: qmstr
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: qmstr-master
        image: endocodeci/qmstr-master
        command: [ "/usr/local/bin/qmstr-master" ]
        args: [ "--config", "/home/qmstr/config/qmstr.yaml"]
        ports:
        - containerPort: 50051
        env:
        - name: SERVER_BUILDPATH
          value: "/var/qmstr/buildroot"
        volumeMounts:
        - name: config-volume
          mountPath: /home/qmstr/config/
        - name: buildroot-volume
          mountPath: /var/qmstr/buildroot/
      - name: qmstr-client
        image: endocodeci/qmstr-client-mvn
        command: [ "sh", "-c", "mvn package -Dmaven.test.skip=true" ]
        env:
        - name: QMSTRADDRENV
          value: "localhost:50051"
        - name: BUILDROOT
          value: /var/qmstr/buildroot
        volumeMounts:
        - name: buildroot-volume
          mountPath: /var/qmstr/buildroot
      initContainers:
      - name: repo-cloner
        image: k8s.gcr.io/git-sync:v3.1.6
        env:
          - name: GIT_SYNC_REPO # overridable
            value: https://github.com/google/guava.git
          - name: GIT_SYNC_ROOT
            value: /home/git/buildroot
          - name: GIT_SYNC_DEST
            value: project
          - name: GIT_SYNC_ONE_TIME # exit after the initial checkout
            value: "1"
          - name: GIT_SYNC_DEPTH # shallow clone
            value: "1"
          - name: GIT_SYNC_SUBMODULES # shallow submodules
            value: "shallow"
        volumeMounts:
          - name: buildroot-volume
            mountPath: /home/git/buildroot
        securityContext:
          runAsUser: 0
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /buildroot"]
        volumeMounts:
          - name: buildroot-volume
            mountPath: /buildroot
      - name: pom-patch
        image: endocodeci/pom-patch
        command: ["python", "insert-build-plugin.py", "qmstr-maven-plugin.xml"]
        volumeMounts:
        - name: buildroot-volume
          mountPath: /home/configure/buildroot
      volumes:
      - name: buildroot-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: qmstr-config
          items:
          - key: qmstr.yaml
            path: qmstr.yaml

