project:
  name: "CI"
  metadata:
    message: "Hello World!"
  server:
    dbAddress: "dgraph:9080"
    rpcAddress: "localhost:50051"
  analysis:
    - analyzer: scancode-analyzer
      name: "Scancode Analyzer"
      config:
        workdir: "/var/qmstr/buildroot/project"
        resultfile: "/var/qmstr/buildroot/scancode.json"
#       cached: "true"
