# This is a basic workflow to help you get started with Actions
# Demodemo
name: Publish Docker
on:
  push:

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: qmstr-dev
  GKE_ZONE: europe-west3-a
  GOBUILDER_IMAGE: "golang:1.12-buster"
  
jobs:
  build-master:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout VCS
      uses: actions/checkout@master

    - name: Set env
      run: echo ::set-env name=DOCKER_BUILDKIT::1

    - name: Build and Push
      uses: docker/build-push-action@v1
      with:
        repository: endocodeci/qmstr-master
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/qmstr-master/Dockerfile
        tag_with_sha: true
        push: true
      
  build-client:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout VCS
      uses: actions/checkout@master

    - name: Set env
      run: |
        echo ::set-env name=GITHUB_SHA_SHORT::$(git rev-parse --short $GITHUB_SHA)
        echo ::set-env name=DOCKER_BUILDKIT::1

    - name: Build and Push Base Client
      uses: docker/build-push-action@v1
      with:
        repository: endocodeci/qmstr-client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/qmstr-client/Dockerfile
        target: base
        tag_with_sha: true

    - name: Build and Push Maven Client
      uses: docker/build-push-action@v1
      with:
        repository: endocodeci/qmstr-client-mvn
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/qmstr-client/Dockerfile
        target: mvn
        tag_with_sha: true

  build-init-containers:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout VCS
      uses: actions/checkout@master

    - name: Set env
      run: |
        echo ::set-env name=GITHUB_SHA_SHORT::$(git rev-parse --short $GITHUB_SHA)

    - name: Build and push endocodeci/pom-patch
      uses: docker/build-push-action@v1
      with:
        repository: endocodeci/pom-patch
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/init/pom-patch/Dockerfile
        tag_with_sha: true

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: [build-master, build-client, build-init-containers]
    
    steps:

    - name: Checkout VCS
      uses: actions/checkout@master

    - name: Set env
      run: echo ::set-env name=GITHUB_SHA_SHORT::$(git rev-parse --short $GITHUB_SHA)
      
    - name: Setup Google SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.SA_EMAIL_DEPLOY_QMSTR_DEV }}
        service_account_key: ${{ secrets.SA_KEY_DEPLOY_QMSTR_DEV }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@master
      with:
        kustomize-version: "3.2.1"

    - name: Make kustomize executable
      run: chmod +x /opt/hostedtoolcache/kustomize/3.2.1/x64/kustomize
        
    - name: Deploy to Dev Cluster
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
        --zone $GKE_ZONE --project $GKE_PROJECT
        cd ./deploy
        export SHA_TAG="sha-${{ env.GITHUB_SHA_SHORT }}"
        export NAMESPACE="qmstr-$SHA_TAG"
        kubectl create namespace $NAMESPACE
        kustomize edit set namespace $NAMESPACE
        kustomize edit set image endocodeci/qmstr-master:$SHA_TAG
        kustomize edit set image endocodeci/qmstr-client-mvn:$SHA_TAG
        kustomize edit set image endocodeci/pom-patch:$SHA_TAG
        kustomize build . | kubectl apply -f -

